"""DSL 语法模块 - 解析器与 AST 定义

提供工作流 DSL 的语法解析能力，将 .wf 文本转换为 AST。
引擎通过此模块感知语法，无需关注解析细节。
"""

from .ast_nodes import (
    And,
    ArithOp,
    Break,
    ByClause,
    CallProc,
    # 语句节点
    Click,
    Collect,
    Contains,
    Continue,
    CoordPoint,
    Drag,
    # 表达式节点
    EntityRef,
    Equals,
    Eval,
    EvalFieldChainAssign,
    FieldAccess,
    Find,
    For,
    ForRange,
    FuncCall,
    Goto,
    GreaterEqual,
    GreaterThan,
    If,
    Import,
    InList,
    IsEmpty,
    KeywordRef,
    Label,
    LessEqual,
    LessThan,
    Literal,
    Log,
    Loop,
    Move,
    Not,
    NotEqual,
    NumericEqual,
    Or,
    PanelGridDrag,
    PanelRef,
    Place,
    Press,
    PressMode,
    ProcDef,
    # 程序
    Program,
    Recognize,
    Return,
    Scan,
    Screenshot,
    Scroll,
    Try,
    TupleLiteral,
    UntilLoop,
    VarRef,
    Wait,
    WaitStable,
    WhereClause,
    WhileLoop,
)
from .parser import parse_file, parse_text

__all__ = [
    "parse_file", "parse_text",
    "Program",
    "Click", "Place", "Move", "Scroll", "Drag", "Press", "Wait", "WaitStable", "Scan", "Recognize", "Collect", "Log", "Screenshot", "Find",
    "Import", "ProcDef", "CallProc",
    "If", "For", "ForRange", "Loop", "WhileLoop", "UntilLoop", "Break", "Continue", "Return", "Label", "Goto", "Try",
    "Eval", "EvalFieldChainAssign", "FuncCall",
    "EntityRef", "PanelRef", "PanelGridDrag", "VarRef", "KeywordRef", "Literal", "FieldAccess", "CoordPoint", "ByClause", "WhereClause",
    "Contains", "Equals", "InList", "IsEmpty",
    "GreaterThan", "LessThan", "GreaterEqual", "LessEqual", "NotEqual", "NumericEqual",
    "Not", "And", "Or", "ArithOp",
    "TupleLiteral",
    "PressMode",
]
