content_version: 1
key: heal_fire
name: 治疗火拳
default_rating: excellent
playstyles:
- 火拳
transmute_priority:
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大牵丝攻击
affix_pool:
- 对首领单位增伤
- 单体类奇术增伤
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 精准率
- 最大无相攻击
- 最大牵丝攻击
- 势
common_conditions:
  normal_conditions:
  - count_max:
      symbols:
      - 最大外功攻击
      max: 0
  excellent_conditions:
  - count_min:
      symbols:
      - 势
      min: 1
patterns:
  主武器:
    first:
    - 最大外功攻击
    normal_conditions:
    - count_max:
        symbols:
        - 劲
        - 最大外功攻击
        max: 0
    - - count_min:
          symbols:
          - 势
          min: 1
      - count_min:
          symbols:
          - 会心率
          - 精准率
          min: 1
    top_conditions:
    - - count_max:
          symbols:
          - 最大无相攻击
          max: 0
      - not_together:
        - 敏
        - 会心率
  副武器:
    first:
    - 最大外功攻击
    normal_conditions:
    - count_max:
        symbols:
        - 劲
        - 最大外功攻击
        max: 0
    - - count_min:
          symbols:
          - 势
          min: 1
      - count_min:
          symbols:
          - 会心率
          - 精准率
          min: 1
    top_conditions:
    - - count_max:
          symbols:
          - 最大无相攻击
          max: 0
      - not_together:
        - 敏
        - 会心率
  环:
    first:
    - 最大外功攻击
    normal_conditions:
    - count_max:
        symbols:
        - 劲
        - 最大外功攻击
        max: 0
    - - count_min:
          symbols:
          - 势
          min: 1
      - count_min:
          symbols:
          - 会心率
          - 精准率
          min: 1
    top_conditions:
    - - count_max:
          symbols:
          - 最大牵丝攻击
          max: 0
      - not_together:
        - 敏
        - 会心率
  冠胄:
    first:
    - 会心率
    - 精准率
    junk_conditions:
    - count_max:
        symbols:
        - 单体类奇术增伤
        max: 0
    top_conditions:
    - count_max:
        symbols:
        - 最大牵丝攻击
        max: 0
  胫甲:
    first:
    - 劲
    junk_conditions:
    - count_max:
        symbols:
        - 对首领单位增伤
        max: 0
    top_conditions:
    - count_max:
        symbols:
        - 会心率
        - 精准率
        - 最大牵丝攻击
        max: 0
