key: heal_fire
name: 治疗火拳
order: 41
playstyles:
  火拳:
    main:
      weapon: 扇
      damage: null
    sub:
      weapon: 伞
      damage: null
    attr: 牵丝
transmute_priority:
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大牵丝攻击
affix_pool:
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大牵丝攻击
- 精准率
- 势
- 单体类奇术增伤
- 对首领单位增伤
patterns:
  主武器:
    first:
    - 最大外功攻击
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 最小外功攻击
      - 劲
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
  副武器:
    first:
    - 最大外功攻击
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 最小外功攻击
      - 劲
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
  环:
    first:
    - 最大外功攻击
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 最小外功攻击
      - 劲
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
  冠胄:
    first:
    - 会心率
    junk_conditions:
    - not_contains:
      - 单体类奇术增伤
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    top_conditions:
    - not_contains:
      - 最大无相攻击
  胫甲:
    first:
    - 劲
    junk_conditions:
    - not_contains:
      - 对首领单位增伤
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    top_conditions:
    - not_contains:
      - 最大无相攻击
      - 会心率
      - 精准率
