key: heal_pure
name: 治疗纯奶
order: 40
playstyles:
  纯奶:
    main:
      weapon: 扇
      damage: 扇武学增效
    sub:
      weapon: 伞
      damage: null
    attr: 牵丝
transmute_priority:
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大牵丝攻击
affix_pool:
- 最大外功攻击
- 劲
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大牵丝攻击
- 势
- 全武学增效
- 对玩家单位增效
patterns:
  主武器:
    first:
    - 最大外功攻击
    - 最小外功攻击
    usable_conditions:
    - not_contains:
      - 最大外功攻击
      - 最小外功攻击
      - 劲
    top_conditions:
    - not_contains:
      - 会心率
      - 最大无相攻击
  副武器:
    first:
    - 最大外功攻击
    - 最小外功攻击
    usable_conditions:
    - count_max:
        symbols:
        - 最大外功攻击
        - 最小外功攻击
        - 劲
        max: 1
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
  环:
    first:
    - 最大外功攻击
    - 最小外功攻击
    junk_conditions:
    - not_contains:
      - 全武学增效
    usable_conditions:
    - not_contains:
      - 最大外功攻击
      - 最小外功攻击
      - 劲
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
  冠胄:
    first:
    - 会心率
    usable_conditions:
    - count_max:
        symbols:
        - 最大外功攻击
        - 最小外功攻击
        - 劲
        max: 1
    top_conditions:
    - not_contains:
      - 最大无相攻击
  胫甲:
    first:
    - 劲
    junk_conditions:
    - not_contains:
      - 对玩家单位增效
    usable_conditions:
    - not_contains:
      - 最大外功攻击
      - 最小外功攻击
      - 劲
    top_conditions:
    - - not_contains:
        - 最大无相攻击
      - not_together:
        - 敏
        - 会心率
