key: huixin_small
name: 会心小外
default_rating: excellent
quality_thresholds:
  佩:
  - gold
  - purple
playstyles:
  纯唐:
    main:
      weapon: 横刀
      damage: 横刀武学增伤
    sub:
      weapon: 陌刀
      damage: null
    attr: 裂石
  双切:
    main:
      weapon: 陌刀
      damage: 陌刀武学增伤
    sub:
      weapon: 横刀
      damage: null
    attr: 裂石
  破竹鸢:
    main:
      weapon: 手甲
      damage: 手甲武学增伤
    sub:
      weapon: 绳镖
      damage: null
    attr: 破竹
  双刀:
    main:
      weapon: 双刀
      damage: 双刀武学增伤
    sub:
      weapon: 绳镖
      damage: 绳镖武学增伤
    attr: 破竹
  尘尘:
    main:
      weapon: 伞
      damage: 伞武学增效
    sub:
      weapon: 绳镖
      damage: null
    attr: 破竹
  翊翊(不推荐):
    main:
      weapon: 舞绫鼓
      damage: 舞绫鼓武学增伤
    sub:
      weapon: 扇
      damage: null
    attr: 牵丝
transmute_priority:
- 最小外功攻击
- 敏
- 最大无相攻击
- 最大本属攻击
- 会心率
affix_pool:
- 对首领单位增伤
- 全武学增效
- 最小外功攻击
- 敏
- 会心率
- 最大无相攻击
- 最大本属攻击
- 精准率
- 最小无相攻击
- 最小本属攻击
- 最小外属攻击
- 单体类奇术增伤
- 对玩家单位增效
common_conditions:
  junk_conditions:
  - count_min:
      symbols:
      - 最小本属攻击
      - 最小外属攻击
      min: 2
  normal_conditions:
  - count_min:
      symbols:
      - 最小本属攻击
      - 最小外属攻击
      min: 1
  - count_max:
      symbols:
      - 最小外功攻击
      max: 0
patterns:
  主武器:
    first:
    - 最小外功攻击
    top_conditions:
    - contains_all:
      - 最小外功攻击
      - 敏
      - 最大无相攻击
  副武器:
    first:
    - 最小外功攻击
    top_conditions:
    - contains_all:
      - 最小外功攻击
      - 敏
      - 最大无相攻击
  环:
    first:
    - 最小外功攻击
    junk_conditions:
    - count_max:
        symbols:
        - 全武学增效
        max: 0
    top_conditions:
    - - contains_all:
        - 最小外功攻击
        - 敏
      - count_min:
          symbols:
          - 会心率
          - 精准率
          - 最大本属攻击
          min: 1
  冠胄:
    first:
    - 会心率
    - 精准率
    junk_conditions:
    - when:
        keep_danti: false
      all:
      - count_min:
          symbols:
          - 单体类奇术增伤
          min: 1
    top_conditions:
    - - contains_all:
        - 最小外功攻击
        - 敏
        - 最大本属攻击
      - count_min:
          symbols:
          - 会心率
          - 精准率
          min: 1
      - count_max:
          symbols:
          - 精准率
          max: 1
          include_first: true
  胫甲:
    first:
    - 会心率
    - 精准率
    junk_conditions:
    - when:
        keep_wanjia: false
      all:
      - count_max:
          symbols:
          - 对首领单位增伤
          max: 0
    - when:
        keep_wanjia: false
      all:
      - count_min:
          symbols:
          - 对玩家单位增效
          min: 1
    - when:
        keep_wanjia: true
      all:
      - count_max:
          symbols:
          - 对首领单位增伤
          - 对玩家单位增效
          max: 0
    top_conditions:
    - contains_all:
      - 最小外功攻击
      - 敏
      - 最大本属攻击
