key: huixin_small
name: 会心流派-小外流
order: 20
has_keep_pvp: true
needs_sub_school: true
sub_school_label: 指定流派（必选）：
sub_schools:
  lieshi:
    name: 裂石
    playstyles:
      chuntang: 纯唐
      shuangqie: 双切
  pozhu:
    name: 破竹
  qiansi:
    name: 牵丝
    playstyles:
      zoudi: 走地
      feitian: 飞天
own_attr: from_sub_schools
weapons:
  lieshi.chuntang:
    main:
      横刀: 横刀武学增伤
    sub:
    - 陌刀
  lieshi.shuangqie:
    main:
      陌刀: 陌刀武学增伤
    sub:
    - 横刀
  pozhu:
    main:
      双刀: 双刀武学增伤
      伞: 伞武学增伤
      手甲: 手甲武学增伤
    sub:
    - 绳镖
  qiansi:
    main:
      伞: 伞武学增伤
      舞绫鼓: 舞绫鼓武学增伤
    sub:
    - 扇
transmute_priority:
- 最小外功攻击
- 敏
- 最大无相攻击
- 会心率
affix_pool:
- 最小外功攻击
- 敏
- 会心率
- 精准率
- 最大无相攻击
- 最小无相攻击
- 最小鸣金攻击
- 最小裂石攻击
- 最小破竹攻击
- 最小牵丝攻击
junk_rules: []
patterns:
  副武器:
    first:
    - 最小外功攻击
    required:
    - - 最小外功攻击
    - - 敏
    required_damage: null
    optional_n: 2
    top:
    - not_contains:
      - 最小无相攻击
      - 最小鸣金攻击
      - 最小裂石攻击
      - 最小破竹攻击
      - 最小牵丝攻击
      - 精准率
  环:
    first:
    - 最小外功攻击
    required:
    - - 全武学增效
    - - 最小外功攻击
    required_damage: 全武学增效
    optional_n: 2
    top:
    - not_contains:
      - 最小无相攻击
      - 最小鸣金攻击
      - 最小裂石攻击
      - 最小破竹攻击
      - 最小牵丝攻击
      - 精准率
  冠胄:
    first:
    - 会心率
    - 精准率
    required:
    - - 最小外功攻击
    - - 敏
      - 最大无相攻击
    required_damage: null
    optional_n: 2
    allowed_divine_pvp:
    - 单体类奇术增伤
    top:
    - not_contains:
      - 最小无相攻击
      - 最小鸣金攻击
      - 最小裂石攻击
      - 最小破竹攻击
      - 最小牵丝攻击
    - count_max:
        symbols:
        - 精准率
        max: 1
        include_first: true
  胫甲:
    first:
    - 会心率
    - 精准率
    required:
    - - 对首领单位增伤
    - - 最小外功攻击
    required_damage: 对首领单位增伤
    damage_pvp_substitute: 对玩家单位增效
    optional_n: 2
    top:
    - not_contains:
      - 最小无相攻击
      - 最小鸣金攻击
      - 最小裂石攻击
      - 最小破竹攻击
      - 最小牵丝攻击
    - not_contains:
      - 会心率
      - 精准率
  主武器:
    first:
    - 最小外功攻击
    required:
    - - DMG
    - - 最小外功攻击
    required_damage: DMG
    optional_n: 2
    top:
    - not_contains:
      - 最小无相攻击
      - 最小鸣金攻击
      - 最小裂石攻击
      - 最小破竹攻击
      - 最小牵丝攻击
      - 精准率
