key: huiyi_general
name: 会意通用
order: 10
weapon_rules:
  会意:
    main:
      weapon: 剑
      damage: 剑武学增伤
    sub:
      weapon: 枪
      damage: null
transmute_priority:
- 最大外功攻击
- 势
- 劲
- 会意率
- 最大无相攻击
- 最大鸣金攻击
affix_pool:
- 最大外功攻击
- 势
- 劲
- 会意率
- 最大无相攻击
- 最大鸣金攻击
- 会心率
- 精准率
- 全武学增效
- 对首领单位增伤
patterns:
  主武器:
    first:
    - 最大外功攻击
    junk_conditions:
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 2
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 劲
      - 势
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 1
    top_conditions:
    - not_contains:
      - 会意率
      - 最大无相攻击
  副武器:
    first:
    - 最大外功攻击
    junk_conditions:
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 2
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 劲
      - 势
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 1
    top_conditions:
    - contains_all:
      - 劲
      - 势
  环:
    first:
    - 最大外功攻击
    junk_conditions:
    - not_contains:
      - 全武学增效
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 2
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 1
    top_conditions:
    - contains_all:
      - 劲
      - 势
  冠胄:
    first:
    - 会意率
    junk_conditions:
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 2
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - not_contains:
      - 劲
      - 势
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 1
    top_conditions:
    - not_contains:
      - 最大鸣金攻击
  胫甲:
    first:
    - 劲
    junk_conditions:
    - not_contains:
      - 对首领单位增伤
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 2
    usable_conditions:
    - not_contains:
      - 最大外功攻击
    - count_min:
        symbols:
        - 会心率
        - 精准率
        min: 1
    top_conditions:
    - contains_all:
      - 劲
      - 势
