key: huiyi_general
name: 会意流派-通用
order: 10
has_keep_pvp: true
needs_sub_school: false
own_attr: 鸣金
weapons:
  default:
    main:
      剑: 剑武学增伤
    sub:
    - 枪
transmute_priority:
- 最大外功攻击
- 势
- 劲
- 会意率
- 最大无相攻击
affix_pool:
- 最大外功攻击
- 势
- 劲
- 会意率
- 最大无相攻击
- 会心率
- 精准率
optional_pool:
- 劲
- 势
- 会意率
- 最大无相攻击
junk_rules:
- count_min:
    symbols:
    - 会心率
    - 精准率
    min: 2
patterns:
  主武器:
    first:
    - 最大外功攻击
    required:
    - - DMG
    - - 最大外功攻击
    - - 劲
      - 势
    required_damage: DMG
    optional_n: 1
    top:
    - not_contains:
      - 会意率
      - 最大无相攻击
  环:
    first:
    - 最大外功攻击
    required:
    - - 最大外功攻击
    - - 全武学增效
    required_damage: 全武学增效
    optional_n: 2
    top:
    - contains_all:
      - 劲
      - 势
  冠胄:
    first:
    - 会意率
    required:
    - - 最大外功攻击
    - - 劲
      - 势
    required_damage: null
    optional_n: 2
    allowed_divine_pvp:
    - 单体类奇术增伤
    top:
    - not_contains:
      - 最大无相攻击
  胫甲:
    first:
    - 劲
    required:
    - - 对首领单位增伤
    - - 最大外功攻击
    required_damage: 对首领单位增伤
    damage_pvp_substitute: 对玩家单位增效
    optional_n: 2
    top:
    - contains_all:
      - 劲
      - 势
  副武器:
    first:
    - 最大外功攻击
    required:
    - - 最大外功攻击
    - - 劲
      - 势
    required_damage: null
    optional_n: 2
    top:
    - contains_all:
      - 劲
      - 势
