content_version: 1
key: activity_huoyun
name: 货运
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: region
  name: 区域
  type: attr
  is_text: true
  is_clickable: false
