content_version: 1
key: activity_huoyun
name: 货运
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
  views:
  - base
  - baiye
- key: region
  name: 区域
  type: attr
  is_text: true
  is_clickable: false
  view: base
- key: title
  name: 货运轮次
  type: attr
  is_text: true
  is_clickable: false
  view: baiye
- key: material_name
  name: 选中材料
  type: attr
  is_text: true
  is_clickable: false
  view: baiye
- key: material_count
  name: 持有与需求数量
  type: attr
  is_text: true
  is_clickable: false
  view: baiye
- key: materials
  name: 货运材料列表
  type: func
  is_text: true
  is_clickable: true
  view: baiye
- key: get_sources
  name: 获取途径
  type: func
  is_text: true
  is_clickable: true
  view: baiye
- key: submit
  name: 提交材料
  type: func
  is_text: true
  is_clickable: true
  view: baiye
- key: round_progress
  name: 本轮提交进度
  type: attr
  is_text: true
  is_clickable: false
  view: baiye
- key: round_chest
  name: 本轮奖励宝箱
  type: func
  is_text: false
  is_clickable: true
  view: baiye
- key: source_panel
  name: 获取途径浮层
  type: func
  is_text: true
  is_clickable: true
  view: sources
- key: sources_close
  name: 关闭获取途径
  type: func
  is_text: false
  is_clickable: true
  view: sources
- key: reward_title
  name: 奖励一览
  type: attr
  is_text: true
  is_clickable: false
  view: reward
- key: reward_claim
  name: 领取本轮奖励
  type: func
  is_text: true
  is_clickable: true
  view: reward
- key: reward_back
  name: 关闭奖励一览
  type: func
  is_text: false
  is_clickable: true
  view: reward
views:
- key: base
  name: 货运
- key: baiye
  name: 百业货运
- key: sources
  name: 物品获取途径
  same_layer: false
- key: reward
  name: 本轮奖励
  same_layer: false
points:
- key: material_1
  name: 上排1
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_2
  name: 上排2
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_3
  name: 上排3
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_4
  name: 上排4
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_5
  name: 下排可见区1
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_6
  name: 下排可见区2
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_7
  name: 下排可见区3
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: material_8
  name: 下排可见区4
  type: slot
  is_text: false
  is_clickable: true
  view: baiye
- key: sources_scroll_start
  name: 途径列表向上划起点
  type: func
  is_text: false
  is_clickable: true
  view: sources
- key: sources_scroll_end
  name: 途径列表向上划终点
  type: func
  is_text: false
  is_clickable: true
  view: sources
