key: action_control
name: 动作
views:
- key: base
  name: 基底
- key: camera
  name: 拍照
regions:
- key: back_confirm
  name: 拍照返回确认
  type: func
  is_text: true
  is_clickable: true
  view: camera
- key: camera_shot
  name: 拍照
  type: func
  is_text: false
  is_clickable: true
  view: camera
