content_version: 1
key: activity_fujingxingzhou
name: 浮景行舟
views:
- key: base
  name: 基底
regions:
- key: limited_list
  name: 限时活动列表
  type: attr
  is_text: true
  is_clickable: false
- key: welfare
  name: 画舫福利
  type: attr
  is_text: true
  is_clickable: false
- key: score
  name: 福缘积分
  type: attr
  is_text: true
  is_clickable: false
- key: return_to_boat
  name: 回到船上
  type: func
  is_text: true
  is_clickable: true
- key: channel_tab
  name: 频道页签
  type: func
  is_text: true
  is_clickable: true
- key: channel_list
  name: 频道列表
  type: attr
  is_text: true
  is_clickable: false
- key: channel_title
  name: 当前频道
  type: attr
  is_text: true
  is_clickable: false
- key: messages
  name: 频道消息
  type: attr
  is_text: true
  is_clickable: false
- key: new_messages
  name: 新消息
  type: func
  is_text: true
  is_clickable: true
- key: invite_arrow
  name: 邀约箭头横向锚点
  type: func
  is_text: false
  is_clickable: true
- key: activity_board
  name: 棋局上阵状态
  type: attr
  is_text: true
  is_clickable: false
- key: activity_exit
  name: 棋局退出
  type: func
  is_text: true
  is_clickable: true
- key: ship_exit
  name: 退出画舫
  type: func
  is_text: false
  is_clickable: true
- key: confirm_label
  name: 退出提示
  type: attr
  is_text: true
  is_clickable: false
- key: confirm
  name: 退出确认
  type: func
  is_text: true
  is_clickable: true
- key: result_continue
  name: 棋局结算继续
  type: func
  is_text: true
  is_clickable: true
- key: reward_title
  name: 获得物品
  type: attr
  is_text: true
  is_clickable: false
- key: reward_blank
  name: 关闭奖励提示
  type: func
  is_text: false
  is_clickable: true
- key: ship_result
  name: 画舫结算积分
  type: attr
  is_text: true
  is_clickable: false
