content_version: 1
key: appearance_main
name: 外观
views:
- key: base
  name: 衣柜
  kind: page
- key: qingjing
  name: 情境
  kind: tab
  owner: /base
- key: chuanda
  name: 穿搭方案
  kind: page
- key: qingjing_editing
  name: 情境编辑
  kind: page
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
  views:
  - base
  - qingjing
  - chuanda
  - qingjing_editing
  to: "@caller"
- key: yigui
  name: 衣柜
  type: func
  is_text: true
  is_clickable: true
  views:
  - base
  - qingjing
  to: /base
  navigation: switch
- key: qingjing
  name: 情境
  type: func
  is_text: true
  is_clickable: true
  views:
  - base
  - qingjing
  to: /qingjing
  navigation: switch
- key: chuanda
  name: 穿搭方案
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /chuanda
  navigation: open
- key: edit_qingjing
  name: 编辑情境
  type: func
  is_text: true
  is_clickable: true
  view: qingjing
  to: /qingjing_editing
  navigation: open
- key: fangan_1
  name: 方案1
  type: func
  is_text: false
  is_clickable: true
  view: chuanda
- key: taoyong
  name: 套用方案
  type: func
  is_text: true
  is_clickable: true
  view: chuanda
- key: save
  name: 保存
  type: func
  is_text: true
  is_clickable: true
  view: qingjing_editing
