key: bag_equip_detail
name: 装备
views:
- key: base
  name: 基底
- key: kuaijie
  name: 快捷道具
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: main_weapon
  name: 主武器
  type: slot
  is_text: false
  is_clickable: true
- key: sub_weapon
  name: 副武器
  type: slot
  is_text: false
  is_clickable: true
- key: ring
  name: 环
  type: slot
  is_text: false
  is_clickable: true
- key: pendant
  name: 佩
  type: slot
  is_text: false
  is_clickable: true
- key: head
  name: 冠胄
  type: slot
  is_text: false
  is_clickable: true
- key: chest
  name: 胸甲
  type: slot
  is_text: false
  is_clickable: true
- key: leg
  name: 胫甲
  type: slot
  is_text: false
  is_clickable: true
- key: wrist
  name: 腕甲
  type: slot
  is_text: false
  is_clickable: true
- key: bow
  name: 弓箭
  type: slot
  is_text: false
  is_clickable: true
- key: arrow
  name: 射玦
  type: slot
  is_text: false
  is_clickable: true
- key: back_to_all
  name: 退回全部
  type: func
  is_text: false
  is_clickable: true
- key: peiyang
  name: 培养
  type: func
  is_text: false
  is_clickable: true
- key: item
  name: 道具
  type: func
  is_text: false
  is_clickable: true
- key: renwu
  name: 任务
  type: func
  is_text: false
  is_clickable: true
- key: qiandai
  name: 钱袋
  type: func
  is_text: false
  is_clickable: true
- key: sub_equip
  name: 装备
  type: func
  is_text: true
  is_clickable: true
- key: sub_quick
  name: 快捷道具
  type: func
  is_text: true
  is_clickable: true
- key: sub_baoguo
  name: 子包裹
  type: attr
  is_text: true
  is_clickable: false
- key: recycle
  name: 回收装备
  type: func
  is_text: true
  is_clickable: true
- key: zhengli
  name: 整理背包
  type: func
  is_text: true
  is_clickable: true
- key: zhizao
  name: 制造
  type: func
  is_text: true
  is_clickable: true
panels:
- key: bag_grid
  name: 背包网格
  min_visible: 0.85
