key: equip_tune_result
name: 调律结果

regions:
  - key: tune_affix
    name: 调律词条
    type: attr

  - key: tune_tip
    name: 调律提示
    type: attr

  - key: close_btn
    name: 关闭
    type: func
    is_text: false
    is_clickable: true
