content_version: 1
key: equip_tune_detail
name: 调律
views:
- key: base
  name: 基底
- key: result
  name: 调律结果
  same_layer: false
- key: reset_tune
  name: 重置调律
  same_layer: false
- key: reset_confirm
  name: 重置确认
  same_layer: false
- key: return_good
  name: 狗粮返还
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
  view: base
- key: affix_gong
  name: 词条宫
  type: attr
  is_text: true
  is_clickable: false
- key: affix_shang
  name: 词条商
  type: attr
  is_text: true
  is_clickable: false
- key: affix_jue
  name: 词条角
  type: attr
  is_text: true
  is_clickable: false
- key: affix_zhi
  name: 词条徵
  type: attr
  is_text: true
  is_clickable: false
- key: affix_yu
  name: 词条羽
  type: attr
  is_text: true
  is_clickable: false
- key: auto_add
  name: 一键添加
  type: func
  is_text: true
  is_clickable: true
- key: tune_btn
  name: 调律
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /result
- key: auto_add_2
  name: 未展开提示
  type: func
  is_text: true
  is_clickable: true
- key: expand
  name: 展开
  type: func
  is_text: false
  is_clickable: true
- key: tune_affix
  name: 调律词条
  type: attr
  is_text: true
  is_clickable: false
  view: result
- key: tune_tip
  name: 调律提示
  type: attr
  is_text: true
  is_clickable: false
  view: result
- key: close_btn
  name: 关闭
  type: func
  is_text: false
  is_clickable: true
  views:
  - result
  - return_good
  to: /base
- key: reset_tune
  name: 重置调律
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /reset_tune
- key: reset_confirm
  name: 确认重置
  type: func
  is_text: true
  is_clickable: true
  view: reset_tune
  to: /reset_confirm
- key: reset_check
  name: 冷静期检查
  type: attr
  is_text: true
  is_clickable: false
  view: reset_tune
- key: reset_info
  name: 材料信息
  type: attr
  is_text: true
  is_clickable: false
  view: reset_tune
- key: reset_back
  name: 重置返回
  type: attr
  is_text: true
  is_clickable: true
  view: reset_tune
  to: /base
panels:
- key: materials
  name: 材料格
  min_visible: 0.95
  calibration: even
  scroll_direction: none
references:
- scene: general_control
  entity: confirm
  view: reset_confirm
- scene: general_control
  entity: cancel
  view: reset_confirm
- scene: general_control
  entity: blank_area
  view: return_good
