key: equip_armor_detail
name: 防具
regions:
- key: equip_type
  name: 装备类型
  type: attr
  is_text: true
  is_clickable: false
- key: equip_level
  name: 装备等级
  type: attr
  is_text: true
  is_clickable: false
- key: base_attr
  name: 基础属性1
  type: attr
  is_text: true
  is_clickable: false
- key: base_attr_2
  name: 基础属性2
  type: attr
  is_text: true
  is_clickable: false
- key: affix_gong
  name: 词条宫
  type: attr
  is_text: true
  is_clickable: false
- key: affix_shang
  name: 词条商
  type: attr
  is_text: true
  is_clickable: false
- key: affix_jue
  name: 词条角
  type: attr
  is_text: true
  is_clickable: false
- key: affix_zhi
  name: 词条徵
  type: attr
  is_text: true
  is_clickable: false
- key: affix_yu
  name: 词条羽
  type: attr
  is_text: true
  is_clickable: false
- key: dingyin
  name: 定音
  type: attr
  is_text: true
  is_clickable: false
- key: zaoyi
  name: 装备造诣
  type: attr
  is_text: true
  is_clickable: false
- key: status
  name: 装备状态
  type: attr
  is_text: true
  is_clickable: false
