key: equip_bag_detail
name: 背包详情

fields:
  - key: slot_main_weapon
    name: 主武器
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_sub_weapon
    name: 副武器
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_ring
    name: 环
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_pendant
    name: 佩
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_head
    name: 冠胄
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_chest
    name: 胸甲
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_leg
    name: 胫甲
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_wrist
    name: 腕甲
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_bow
    name: 弓箭
    type: slot
    is_text: false
    is_clickable: true

  - key: slot_arrow
    name: 射玦
    type: slot
    is_text: false
    is_clickable: true
