key: equip_weapon_detail
name: 武器详情

fields:
  - key: equip_type
    name: 装备类型
    type: attr

  - key: equip_level
    name: 装备等级
    type: attr

  - key: base_attr
    name: 基础属性
    type: attr

  - key: affix_gong
    name: 词条宫
    type: attr

  - key: affix_shang
    name: 词条商
    type: attr

  - key: affix_jue
    name: 词条角
    type: attr

  - key: affix_zhi
    name: 词条徵
    type: attr

  - key: affix_yu
    name: 词条羽
    type: attr

  - key: main_func
    name: 主功能
    type: func
    is_text: true
    is_clickable: true

  - key: more_func
    name: 更多功能
    type: func
    is_text: false
    is_clickable: true

  - key: sub_func_1
    name: 次功能1
    type: func
    is_text: true
    is_clickable: true

  - key: sub_func_2
    name: 次功能2
    type: func
    is_text: true
    is_clickable: true

  - key: sub_func_3
    name: 次功能3
    type: func
    is_text: true
    is_clickable: true

  - key: sub_func_4
    name: 次功能4
    type: func
    is_text: true
    is_clickable: true
