content_version: 1
key: equip_weapon_detail
name: 武器
views:
- key: base
  name: 基底
- key: cooldown
  name: 冷却
regions:
- key: affix_gong
  name: 词条宫
  type: attr
  is_text: true
  is_clickable: false
- key: affix_shang
  name: 词条商
  type: attr
  is_text: true
  is_clickable: false
- key: affix_jue
  name: 词条角
  type: attr
  is_text: true
  is_clickable: false
- key: affix_zhi
  name: 词条徵
  type: attr
  is_text: true
  is_clickable: false
- key: affix_yu
  name: 词条羽
  type: attr
  is_text: true
  is_clickable: false
- key: dingyin
  name: 定音
  type: attr
  is_text: true
  is_clickable: false
- key: cooldown_affix_gong
  name: 冷却词条宫
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
- key: cooldown_affix_shang
  name: 冷却词条商
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
- key: cooldown_affix_jue
  name: 冷却词条角
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
- key: cooldown_affix_zhi
  name: 冷却词条徵
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
- key: cooldown_affix_yu
  name: 冷却词条羽
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
- key: cooldown_dingyin
  name: 冷却定音
  type: attr
  is_text: true
  is_clickable: false
  view: cooldown
references:
- scene: equip_detail
  entity: status
- scene: equip_detail
  entity: equip_type
- scene: equip_detail
  entity: zaoyi
- scene: equip_detail
  entity: equip_level
- scene: equip_detail
  entity: base_attr
