content_version: 1
key: game_login_page
name: 登录
views:
- key: base
  name: 基底
- key: accounts
  name: 切换账号
  same_layer: false
- key: users
  name: 切换用户
  same_layer: false
- key: roles
  name: 切换角色
  same_layer: false
- key: loading
  name: 登录画面
  same_layer: false
- key: start
  name: 启动日常
  same_layer: false
- key: exit
  name: 退出登录
  same_layer: false
regions:
- key: more_user
  name: 更多用户
  type: func
  is_text: false
  is_clickable: true
- key: users_icon
  name: 用户icon
  type: func
  is_text: false
  is_clickable: true
  view: base
  to: /accounts
- key: switch_user
  name: 切换账号
  type: attr
  is_text: true
  is_clickable: true
  view: accounts
  to: /users
- key: tap_user
  name: 选择用户
  type: func
  is_text: false
  is_clickable: true
  view: users
- key: login
  name: 登录
  type: func
  is_text: true
  is_clickable: true
  view: users
  to: /base
- key: switch_role
  name: 选择角色
  type: attr
  is_text: true
  is_clickable: true
  view: base
  to: /roles
- key: enter
  name: 进入游戏
  type: func
  is_text: true
  is_clickable: true
  view: roles
  to: /loading
- key: close_btn
  name: 关闭按钮
  type: func
  is_text: true
  is_clickable: true
  view: start
- key: loading
  name: 加载中
  type: attr
  is_text: true
  is_clickable: false
  view: loading
- key: current_role
  name: 当前角色
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /loading
- key: zllj_btn
  name: 战令领奖
  type: func
  is_text: true
  is_clickable: true
  view: start
  to: zhanling_detail
- key: exit_to_desktop
  name: 退至桌面
  type: func
  is_text: true
  is_clickable: true
  view: exit
- key: back_to_login
  name: 返回登录页面
  type: func
  is_text: true
  is_clickable: true
  view: exit
  to: /base
points:
- key: point_1
  name: 点1
  type: attr
  is_text: false
  is_clickable: true
  view: users
- key: point_2
  name: 点2
  type: attr
  is_text: false
  is_clickable: true
  view: users
panels:
- key: role_list
  name: 角色列表
  min_visible: 0.95
  view: roles
  calibration: even
- key: user_list
  name: 用户列表
  min_visible: 0.95
  view: users
  calibration: even
references:
- scene: general_control
  entity: cancel
  view: loading
- scene: general_control
  entity: confirm
  view: loading
