key: game_menu_page
name: 游戏菜单
views:
- key: base
  name: 基底
- key: page_1
  name: 菜单顶页
- key: page_2
  name: 菜单底页
regions:
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: yanji
  name: 燕叽
  type: func
  is_text: false
  is_clickable: true
- key: mail
  name: 邮件
  type: func
  is_text: false
  is_clickable: true
- key: notice
  name: 公告
  type: func
  is_text: false
  is_clickable: true
- key: time
  name: 时间
  type: func
  is_text: false
  is_clickable: true
- key: camera
  name: 拍照
  type: func
  is_text: false
  is_clickable: true
- key: action
  name: 动作
  type: func
  is_text: false
  is_clickable: true
- key: questionnaire
  name: 问卷
  type: func
  is_text: false
  is_clickable: true
- key: settings
  name: 设置
  type: func
  is_text: false
  is_clickable: true
- key: feedback
  name: 反馈
  type: func
  is_text: false
  is_clickable: true
- key: exit
  name: 退出
  type: func
  is_text: false
  is_clickable: true
- key: bag
  name: 包裹
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: train
  name: 培养
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: wulinlu
  name: 武林录
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: shop
  name: 商店
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: activity
  name: 活动
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: appearance
  name: 外观
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: bu_gan
  name: 不肝
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: harmony
  name: 和鸣
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: travel
  name: 同游
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: business
  name: 百业
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: character
  name: 角色
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: quest
  name: 任务
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: battle_pass
  name: 战令
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: avatar
  name: 头像
  type: func
  is_text: false
  is_clickable: true
- key: username
  name: 用户名
  type: attr
  is_text: true
  is_clickable: false
- key: social
  name: 社交
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: menpai
  name: 门派
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: yingsheng
  name: 营生
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: shilian
  name: 试炼
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: bowuzhi
  name: 博物志
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: xiyue
  name: 戏乐
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: wanxiangji
  name: 万象集
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: xuanshang
  name: 悬赏
  type: func
  is_text: true
  is_clickable: true
  view: page_2
- key: home
  name: 家业
  type: func
  is_text: true
  is_clickable: true
  view: page_1
- key: pets
  name: 伙伴
  type: func
  is_text: true
  is_clickable: true
  view: page_1
