key: game_login_page
name: 登录
views:
- key: base
  name: 基底
- key: users
  name: 切换用户
- key: roles
  name: 切换角色
- key: loading
  name: 登录画面
- key: start
  name: 启动日常
regions:
- key: more_user
  name: 更多用户
  type: func
  is_text: false
  is_clickable: true
- key: users_icon
  name: 用户icon
  type: func
  is_text: false
  is_clickable: true
- key: switch_user
  name: 切换账号
  type: attr
  is_text: true
  is_clickable: false
  view: users
- key: tap_user
  name: 选择用户
  type: func
  is_text: false
  is_clickable: true
  view: users
- key: login
  name: 登录
  type: func
  is_text: true
  is_clickable: true
  view: users
- key: user_2
  name: 用户2
  type: func
  is_text: true
  is_clickable: true
  view: users
- key: user_3
  name: 用户3
  type: func
  is_text: true
  is_clickable: true
  view: users
- key: switch_role
  name: 选择角色
  type: attr
  is_text: true
  is_clickable: false
- key: enter
  name: 进入游戏
  type: func
  is_text: true
  is_clickable: true
  view: roles
- key: close_btn
  name: 关闭按钮
  type: func
  is_text: true
  is_clickable: true
  view: start
- key: loading
  name: 加载中
  type: attr
  is_text: true
  is_clickable: false
  view: loading
- key: current_role
  name: 当前角色
  type: func
  is_text: true
  is_clickable: true
- key: zllj_btn
  name: 战令领奖
  type: func
  is_text: true
  is_clickable: true
  view: start
points:
- key: point_1
  name: 点1
  type: attr
  is_text: false
  is_clickable: true
  view: users
- key: point_2
  name: 点2
  type: attr
  is_text: false
  is_clickable: true
  view: users
panels:
- key: role_list
  name: 角色列表
  min_visible: 0.95
  view: roles
  calibration: even
- key: user_list
  name: 用户列表
  min_visible: 0.95
  view: users
  calibration: even
