key: game_main_page
name: 主页
views:
- key: base
  name: 基底
- key: jiugongge
  name: 九宫格
- key: more
  name: 更多
regions:
- key: menu
  name: 菜单
  type: func
  is_text: true
  is_clickable: true
- key: activity
  name: 活动
  type: func
  is_text: true
  is_clickable: true
- key: wulinlu
  name: 武林录
  type: func
  is_text: true
  is_clickable: true
- key: shop
  name: 商店
  type: func
  is_text: true
  is_clickable: true
- key: battle_pass
  name: 战令
  type: func
  is_text: true
  is_clickable: true
- key: harmony
  name: 和鸣
  type: func
  is_text: true
  is_clickable: true
- key: map
  name: 地图
  type: func
  is_text: false
  is_clickable: true
- key: team
  name: 组队
  type: func
  is_text: false
  is_clickable: true
- key: summon_horse
  name: 唤马
  type: func
  is_text: false
  is_clickable: true
- key: listen_wind
  name: 听风辩位
  type: func
  is_text: false
  is_clickable: true
- key: more_func
  name: 更多功能
  type: func
  is_text: false
  is_clickable: true
- key: greet
  name: 动作
  type: func
  is_text: false
  is_clickable: true
- key: chat
  name: 聊天
  type: func
  is_text: false
  is_clickable: true
- key: north
  name: 正北方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: east_north
  name: 东北方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: east
  name: 正东方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: east_south
  name: 东南方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: south
  name: 正南方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: west_south
  name: 西南方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: west
  name: 正西方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: west_north
  name: 西北方
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: center
  name: 中央
  type: attr
  is_text: true
  is_clickable: false
  view: jiugongge
- key: check_left
  name: 确认左区
  type: attr
  is_text: true
  is_clickable: false
  view: more
- key: check_right
  name: 确认右区
  type: attr
  is_text: true
  is_clickable: false
  view: more
points:
- key: origin
  name: 起点
  type: func
  is_text: false
  is_clickable: true
- key: forward
  name: 前进
  type: func
  is_text: false
  is_clickable: true
- key: backward
  name: 后退
  type: func
  is_text: false
  is_clickable: true
- key: turn_left
  name: 向左
  type: func
  is_text: false
  is_clickable: true
- key: turn_right
  name: 向右
  type: func
  is_text: false
  is_clickable: true
