key: general_control
name: 控制
views:
- key: base
  name: 基底
- key: confirm
  name: 确认
- key: fight
  name: 战斗
- key: get_item
  name: 获得箱子
regions:
- key: confirm
  name: 确认
  type: func
  is_text: true
  is_clickable: false
  view: confirm
- key: cancel
  name: 取消
  type: func
  is_text: true
  is_clickable: true
  view: confirm
- key: close_item
  name: 关闭提示
  type: func
  is_text: false
  is_clickable: true
  view: get_item
- key: menu_area
  name: 菜单功能区
  type: attr
  is_text: false
  is_clickable: false
points:
- key: material_slot_1
  name: 材料格1
  type: slot
  is_text: false
  is_clickable: true
- key: material_slot_2
  name: 材料格2
  type: slot
  is_text: false
  is_clickable: true
- key: left_screen_1
  name: 左屏点1
  type: func
  is_text: false
  is_clickable: true
- key: left_screen_2
  name: 左屏点2
  type: func
  is_text: false
  is_clickable: true
- key: equip_slot_1
  name: 背包格1
  type: slot
  is_text: false
  is_clickable: true
- key: equip_slot_2
  name: 背包格2
  type: slot
  is_text: false
  is_clickable: true
- key: menu_point_1
  name: 菜单点1
  type: func
  is_text: false
  is_clickable: true
- key: menu_point_2
  name: 菜单点2
  type: func
  is_text: false
  is_clickable: true
- key: wuxueji
  name: 武学技
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: teshuji
  name: 特殊技
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: qishu
  name: 奇术
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: xieshi
  name: 卸势
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: xuli
  name: 蓄力
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: qingji
  name: 轻击
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: shanbi
  name: 闪避
  type: func
  is_text: false
  is_clickable: true
  view: fight
- key: tiaoyue
  name: 跳跃
  type: func
  is_text: false
  is_clickable: true
  view: fight
