key: general_control
name: 通用控制
regions:
- key: camera_shot
  name: 拍照
  type: func
  is_text: false
  is_clickable: true
- key: back_confirm
  name: 返回确认
  type: func
  is_text: true
  is_clickable: true
points:
- key: material_slot_1
  name: 材料格1
  type: slot
  is_text: false
  is_clickable: true
- key: material_slot_2
  name: 材料格2
  type: slot
  is_text: false
  is_clickable: true
- key: left_screen_1
  name: 左屏点1
  type: func
  is_text: false
  is_clickable: true
- key: left_screen_2
  name: 左屏点2
  type: func
  is_text: false
  is_clickable: true
- key: equip_slot_1
  name: 背包格1
  type: slot
  is_text: false
  is_clickable: true
- key: equip_slot_2
  name: 背包格2
  type: slot
  is_text: false
  is_clickable: true
