content_version: 1
key: general_combat
name: 战斗
regions:
- key: switch
  name: 切换武器
  type: func
  is_text: false
  is_clickable: true
points:
- key: wuxueji
  name: 武学技
  type: func
  is_text: false
  is_clickable: true
- key: teshuji
  name: 特殊技
  type: func
  is_text: false
  is_clickable: true
- key: qishu
  name: 奇术
  type: func
  is_text: false
  is_clickable: true
- key: xieshi
  name: 卸势
  type: func
  is_text: false
  is_clickable: true
- key: xuli
  name: 蓄力
  type: func
  is_text: false
  is_clickable: true
- key: qingji
  name: 轻击
  type: func
  is_text: false
  is_clickable: true
- key: shanbi
  name: 闪避
  type: func
  is_text: false
  is_clickable: true
- key: tiaoyue
  name: 跳跃
  type: func
  is_text: false
  is_clickable: true
- key: qishu_1
  name: 奇术1
  type: func
  is_text: false
  is_clickable: true
- key: qishu_2
  name: 奇术2
  type: func
  is_text: false
  is_clickable: true
- key: qishu_3
  name: 奇术3
  type: func
  is_text: false
  is_clickable: true
- key: qishu_4
  name: 奇术4
  type: func
  is_text: false
  is_clickable: true
- key: bow
  name: 弓箭
  type: func
  is_text: false
  is_clickable: true
