key: general_action
name: 动作
views:
- key: base
  name: 基底
- key: camera
  name: 简单拍照
- key: biaoqing
  name: 表情动作
- key: kanbao
  name: 报纸阅读
regions:
- key: back_confirm
  name: 拍照返回确认
  type: func
  is_text: true
  is_clickable: true
  view: camera
- key: camera_shot
  name: 拍照
  type: func
  is_text: false
  is_clickable: true
  view: camera
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: choose_1
  name: 选择1
  type: func
  is_text: true
  is_clickable: true
  view: kanbao
- key: choose_2
  name: 选择2
  type: func
  is_text: true
  is_clickable: true
  view: kanbao
- key: choose_3
  name: 选择3
  type: func
  is_text: true
  is_clickable: true
  view: kanbao
- key: choose_4
  name: 选择4
  type: func
  is_text: true
  is_clickable: true
  view: kanbao
- key: action_type
  name: 动作分类
  type: func
  is_text: true
  is_clickable: true
  view: biaoqing
panels:
- key: actions
  name: 动作列表
  cols: 6
  rows: 2
  min_visible: 0.95
  view: biaoqing
  calibration: even
  scroll_direction: none
