key: role_detail
name: 角色
regions:
- key: shuxing
  name: 属性
  type: attr
  is_text: true
  is_clickable: true
- key: tizhi
  name: 体质
  type: attr
  is_text: true
  is_clickable: true
- key: mingyu
  name: 名誉
  type: attr
  is_text: true
  is_clickable: true
- key: detail_1
  name: 属性面板_左
  type: attr
  is_text: true
  is_clickable: false
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: detail_2
  name: 属性面板_右
  type: attr
  is_text: true
  is_clickable: false
