content_version: 1
key: shop_detail
name: 商店
views:
- key: base
  name: 基底
- key: jingxuan
  name: 精选
  same_layer: false
- key: jingxuan_daoju
  name: 精选道具
  same_layer: false
regions:
- key: jingxuan
  name: 精选
  type: func
  is_text: true
  is_clickable: true
  views:
  - base
  - jingxuan
  - jingxuan_daoju
  to: /jingxuan
- key: back
  name: 返回
  type: attr
  is_text: true
  is_clickable: false
  views:
  - base
  - jingxuan
panels:
- key: items
  name: 购买列表
  min_visible: 0.95
  view: jingxuan_daoju
  calibration: even
  scroll_direction: none
