content_version: 1
key: training_xinfa
name: 心法
views:
- key: base
  name: 基底
- key: zhihuan
  name: 心得置换
- key: purchase_confirm
  name: 购买确认
- key: recycle_xinfa
  name: 回收书票
regions:
- key: sanben_1
  name: 散本1
  type: attr
  is_text: true
  is_clickable: true
  view: zhihuan
- key: sanben_2
  name: 散本2
  type: attr
  is_text: true
  is_clickable: true
  view: zhihuan
- key: sanben_3
  name: 散本3
  type: attr
  is_text: true
  is_clickable: true
  view: zhihuan
- key: sanben_4
  name: 散本4
  type: attr
  is_text: true
  is_clickable: true
  view: zhihuan
- key: sanben_5
  name: 散本5
  type: attr
  is_text: true
  is_clickable: true
  view: zhihuan
- key: add_all
  name: 添加
  type: func
  is_text: false
  is_clickable: true
  view: zhihuan
- key: purchase
  name: 购买
  type: func
  is_text: true
  is_clickable: true
  view: zhihuan
- key: add_max
  name: 最多
  type: func
  is_text: false
  is_clickable: true
  view: purchase_confirm
- key: confirm
  name: 确认
  type: func
  is_text: true
  is_clickable: true
  view: purchase_confirm
- key: count
  name: 书票数量
  type: attr
  is_text: true
  is_clickable: true
- key: recycle
  name: 回收书票
  type: func
  is_text: true
  is_clickable: true
  view: recycle_xinfa
- key: recycle_entry
  name: 回收入口
  type: func
  is_text: true
  is_clickable: true
  view: zhihuan
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: detail
  name: 详情
  type: func
  is_text: true
  is_clickable: true
- key: exchange
  name: 置换
  type: func
  is_text: true
  is_clickable: true
- key: swap
  name: 转换
  type: func
  is_text: true
  is_clickable: true
- key: num
  name: 可换数量
  type: attr
  is_text: true
  is_clickable: false
  view: zhihuan
