content_version: 1
key: training_main
name: 培养
views:
- key: base
  name: 功法
- key: equip
  name: 装备
  kind: tab
  owner: /base
- key: tianfu
  name: 天赋
  kind: tab
  owner: /base
- key: fangan
  name: 方案
  kind: page
  owner: /base
- key: fangan_fill
  name: 方案_填充
  kind: modal
  owner: /fangan
- key: fangan_confirm
  name: 方案_确认
  kind: modal
  owner: /fangan
regions:
- key: gongfa
  name: 功法
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /base
- key: equip
  name: 装备
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /equip
- key: tianfu
  name: 天赋
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: /tianfu
- key: role
  name: 角色详情
  type: func
  is_text: true
  is_clickable: true
  view: base
  to: role_detail
- key: xinfa
  name: 心法
  type: func
  is_text: false
  is_clickable: true
- key: back
  name: 返回
  type: func
  is_text: false
  is_clickable: true
- key: fangan
  name: 方案管理
  type: func
  is_text: true
  is_clickable: true
  view: base
references:
- scene: general_control
  entity: confirm
  view: fangan_confirm
- scene: general_control
  entity: cancel
  view: fangan_confirm
