content_version: 1
key: training_plan
name: 方案
views:
- key: base
  name: 基底
- key: fill
  name: 填充
  kind: modal
  owner: /base
- key: confirm
  name: 确认
  kind: modal
  owner: /base
regions:
- key: back
  name: 返回培养
  type: func
  is_text: false
  is_clickable: true
  view: base
  to: training_main
- key: plan_title
  name: 当前方案名称
  type: attr
  is_text: true
  is_clickable: false
  view: base
- key: main_art
  name: 方案主武学
  type: attr
  is_text: true
  is_clickable: false
  view: base
- key: sub_art
  name: 方案副武学
  type: attr
  is_text: true
  is_clickable: false
  view: base
- key: use_area
  name: 使用方案按钮区
  type: attr
  is_text: true
  is_clickable: true
  view: base
- key: modal_message
  name: 方案切换提示
  type: attr
  is_text: true
  is_clickable: false
  view: fill
- key: smart_fill
  name: 智能填充
  type: func
  is_text: true
  is_clickable: true
  view: fill
panels:
- key: plan_list
  name: 备战方案列表
  view: base
references:
- scene: general_control
  entity: confirm
  view: confirm
- scene: general_control
  entity: cancel
  view: confirm
