key: ui_school_main
name: 门派首页
regions:
- key: mengui
  name: 门规
  type: func
  is_text: true
  is_clickable: true
- key: diwei
  name: 地位
  type: func
  is_text: true
  is_clickable: true
- key: haoling
  name: 江湖号令
  type: func
  is_text: true
  is_clickable: true
- key: shangdian
  name: 商店
  type: func
  is_text: true
  is_clickable: true
- key: wanfa
  name: 玩法
  type: func
  is_text: true
  is_clickable: true
