version: 1
meta_schema:
- key: level
  name: 等级
  filterable: true
  type: number
  sort_by: desc
  scope: input
- key: level_text
  name: 等级文本区域
  filterable: false
  type: text
  sort_by: asc
  scope: output
  crop:
  - 0.0
  - 0.0
  - 1.0
  - 0.5
- key: count_text
  name: 数量文本区域
  filterable: false
  type: text
  sort_by: asc
  scope: output
  crop:
  - 0.0
  - 0.5
  - 1.0
  - 0.5
references:
- file: 调律材料/94A752E3.png
  label: 彩狗粮
  meta:
    group: 调律材料
    level: '110'
  source: screenshot
  notes: ''
- file: 装备培养/D9C93ECE.png
  label: 装备碎片
  meta:
    level: '110'
    group: 装备培养
  source: screenshot
  notes: ''
- file: 调律材料/4E8AEBCB.png
  label: 金狗粮
  meta:
    level: '110'
    group: 调律材料
  source: screenshot
  notes: ''
- file: 定音转律/CDC5D1DF.png
  label: 止戈定音石
  meta:
    level: '110'
    group: 定音转律
  source: screenshot
  notes: ''
- file: 装备培养/D65E7DA0.png
  label: 啸玉
  meta:
    level: '110'
    group: 装备培养
  source: screenshot
  notes: ''
- file: 定音转律/AF81246E.png
  label: 定音石
  meta:
    level: '110'
    group: 定音转律
  source: screenshot
  notes: ''
- file: 装备培养/1D6D85DB.png
  label: 传律石
  meta:
    level: '110'
    group: 装备培养
  source: screenshot
  notes: ''
- file: 装备培养/71F982EC.png
  label: 承音石
  meta:
    level: '110'
    group: 装备培养
  source: screenshot
  notes: ''
- file: 定音转律/B3D1F2D7.png
  label: 止戈变音石
  meta:
    level: '110'
    group: 定音转律
  source: screenshot
  notes: ''
- file: 定音转律/3C2AFA55.png
  label: 转律石
  meta:
    level: '110'
    group: 定音转律
  source: screenshot
  notes: ''
- file: 调律材料/4BC52A1E.png
  label: 紫狗粮
  meta:
    level: '110'
    group: 调律材料
  source: screenshot
  notes: ''
- file: 调律材料/655A3918.png
  label: 大律准石
  meta:
    level: '110'
    group: 调律材料
  source: screenshot
  notes: ''
- file: 装备培养/F77FFD73.png
  label: 溯玉
  meta:
    group: 装备培养
  source: screenshot
  notes: ''
- file: 调律材料/242A2902.png
  label: 律准石
  meta:
    group: 调律材料
  source: screenshot
  notes: ''
- file: 装备培养/8CFB38DD.png
  label: 振玉
  meta:
    group: 装备培养
  source: screenshot
  notes: ''
- file: 调律材料/453D365A.png
  label: 小律准石
  meta:
    level: '110'
    group: 调律材料
  source: screenshot
  notes: ''
- file: 货币资产/60783429.png
  label: 宋元通宝
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/C7B0F23F.png
  label: 月华通宝
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/8868C5F3.png
  label: 周元通宝
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/416F1E0B.png
  label: 墨筹
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/5FF8C531.png
  label: 长鸣珠
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/08DB0E94.png
  label: 溯玉
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/7A634AB5.png
  label: 花蕊织
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/6E15FF3F.png
  label: 一锭行
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/B0B9EB5C.png
  label: 珍品书票
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/8CAC9D6F.png
  label: 悟真璞
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/80513DA0.png
  label: 四海笺
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/6B69F460.png
  label: 战令币
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/9D0B7228.png
  label: 么玉
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/96978488.png
  label: 金叶子格筹码
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/6BCF8BA3.png
  label: 金谷粒
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/02F63C08.png
  label: 吉金豆
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/B2F51140.png
  label: 长鸣玉
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/366323A8.png
  label: 金宝钞
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/4EA8BF20.png
  label: 宝铢
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/2D5DE2F8.png
  label: 囤囤粟
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/A4DB2CE6.png
  label: 宝钱
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/8CD33FB2.png
  label: 短陌钱
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/A98FF781.png
  label: 和合花钱
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/2FC23098.png
  label: 武魄碎片
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
- file: 货币资产/02B77B98.png
  label: 罪叶
  meta:
    group: 货币资产
  source: screenshot
  notes: ''
