version: 1
meta_schema:
- key: level
  name: 等级
  filterable: true
  type: number
  sort_by: desc
  scope: input
- key: level_text
  name: 等级文本区域
  filterable: false
  type: text
  sort_by: asc
  scope: output
  crop:
  - 0.0
  - 0.0
  - 1.0
  - 0.5
- key: count_text
  name: 数量文本区域
  filterable: false
  type: text
  sort_by: asc
  scope: output
  crop:
  - 0.0
  - 0.5
  - 1.0
  - 0.5
references:
- file: 475BF859.png
  label: 装备碎片
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: D90CF5A6.png
  label: 彩狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: EC3D0E06.png
  label: 金狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: DBFA2793.png
  label: 装备碎片
  meta:
    level: 105
    group: 装备培养
  source: clipboard
  notes: ''
- file: F2130E50.png
  label: 彩狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 946CC90C.png
  label: 金狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 24CCB99E.png
  label: 装备碎片
  meta:
    level: 100
    group: 装备培养
  source: clipboard
  notes: ''
- file: 7D3E1342.png
  label: 金狗粮
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 28ED555E.png
  label: 装备碎片
  meta:
    level: 96
    group: 装备培养
  source: clipboard
  notes: ''
- file: 895530AE.png
  label: 彩狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: B72C379B.png
  label: 金狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 5EE6F5A4.png
  label: 装备碎片
  meta:
    level: 91
    group: 装备培养
  source: clipboard
  notes: ''
- file: DA54B4BF.png
  label: 彩狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 025FE7FC.png
  label: 金狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 7CB8171A.png
  label: 止戈定音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: AA3BBF3B.png
  label: 啸玉
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: 27B17F0B.png
  label: 定音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: EAD816D7.png
  label: 传律石
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: CF813DEE.png
  label: 承音石
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: F476BC36.png
  label: 止戈变音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 5A8FEDD2.png
  label: 变音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 4B117BB7.png
  label: 转律石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 9625FF60.png
  label: 紫狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: DEC6244A.png
  label: 止戈定音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: F3C84593.png
  label: 定音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: 2ED12621.png
  label: 承音石
  meta:
    level: 105
    group: 装备培养
  source: clipboard
  notes: ''
- file: 7D7FF1CB.png
  label: 止戈变音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: D753EFED.png
  label: 转律石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: AE8666A5.png
  label: 紫狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: E07396A6.png
  label: 止戈定音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: 886B3F20.png
  label: 定音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: A775BBF0.png
  label: 传律石
  meta:
    level: 100
    group: 装备培养
  source: clipboard
  notes: ''
- file: A5EE90AA.png
  label: 止戈变音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: FFCBEA1D.png
  label: 紫狗粮
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 9547A900.png
  label: 止戈定音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 6C977B21.png
  label: 定音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 598D48C4.png
  label: 传律石
  meta:
    level: 96
    group: 装备培养
  source: clipboard
  notes: ''
- file: B6F67472.png
  label: 止戈变音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 5CEA3A88.png
  label: 变音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 4EA174CA.png
  label: 转律石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 4D4D9EDB.png
  label: 紫狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: C6F203B0.png
  label: 止戈定音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 1373075E.png
  label: 啸玉
  meta:
    level: 91
    group: 装备培养
  source: clipboard
  notes: ''
- file: FAF61FB3.png
  label: 定音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 33DA4809.png
  label: 止戈变音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: F3FEFBF2.png
  label: 变音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 794E7310.png
  label: 转律石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: B560FFAE.png
  label: 紫狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 26A86377.png
  label: 大律准石
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 188A0FD2.png
  label: 大律准石
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: AF43ACCC.png
  label: 大律准石
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: C4EB10EA.png
  label: 大律准石
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: E525FABE.png
  label: 大律准石
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 8BF65636.png
  label: 溯玉
  meta:
    group: 装备培养
  source: clipboard
  notes: ''
- file: 19C15875.png
  label: 律准石
  meta:
    group: 调律材料
  source: clipboard
  notes: ''
- file: A20C7B45.png
  label: 振玉
  meta:
    group: 装备培养
  source: clipboard
  notes: ''
- file: 80CFEC02.png
  label: 小律准石
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 587E0292.png
  label: 小律准石
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 4476C8DE.png
  label: 小律准石
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 010EE2DC.png
  label: 小律准石
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: E5C29904.png
  label: 小律准石
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 6DAD5F1F.png
  label: 装备匣子
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 63BED34F.png
  label: 金装自选箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: BDE43720.png
  label: 自选词条优
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 5DC3A2EC.png
  label: 自选词条普
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: B8DE1C37.png
  label: 战令经验
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 9AB22E8A.png
  label: 金狗粮追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: C9789D43.png
  label: 定音石追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: A5736562.png
  label: 律准石追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 5AB120F5.png
  label: 金装追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 5E61405F.png
  label: 短陌钱箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: A7BEE0D2.png
  label: 礼物盒
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: B21F3A19.png
  label: 材料箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 93885CB0.png
  label: 武学心得
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 22A110BD.png
  label: 武学突破箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: C3E428E6.png
  label: 武学升级箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 55F6B172.png
  label: 袅袅之音
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 204ECF64.png
  label: 八音窍
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 0269BEFC.png
  label: 绕梁之音
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 99588D75.png
  label: 袅袅非绑
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 5C04CF08.png
  label: 折音券
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 4210FD59.png
  label: 忘川渡
  meta:
    group: 增益道具
  source: clipboard
  notes: ''
- file: 060E5C98.png
  label: 黄泉酿
  meta:
    group: 增益道具
  source: clipboard
  notes: ''
- file: BF46CE97.png
  label: 么玉
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: BD1F0404.png
  label: 长鸣珠
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 182424D9.png
  label: 宝钱
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 52DCBF30.png
  label: 长鸣玉
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 3337014D.png
  label: 宋元通宝
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 73B15299.png
  label: 月华通宝
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 1410245B.png
  label: 周元通宝
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 265F68CE.png
  label: 墨筹
  meta:
    group: 货币资产
  source: clipboard
  notes: ''
- file: 3C45D25D.png
  label: 心法心得
  meta:
    group: 普通道具
  source: screenshot
  notes: ''
match_threshold: 0.35
