version: 1
materials:
- file: 其他培养/E3E6D481.png
  type: 装备碎片
  level: 110
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 调律材料/6E238EAF.png
  type: 彩狗粮
  level: 110
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 调律材料/9A49738F.png
  type: 金狗粮
  level: 110
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 其他培养/2A2F1E2D.png
  type: 装备碎片
  level: 105
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 调律材料/3603D822.png
  type: 彩狗粮
  level: 105
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 调律材料/F729C87E.png
  type: 金狗粮
  level: 105
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 其他培养/7D4FE324.png
  type: 装备碎片
  level: 100
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 调律材料/06A8FCE3.png
  type: 金狗粮
  level: 100
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 其他培养/B5FD6779.png
  type: 装备碎片
  level: 96
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 调律材料/17EDEA11.png
  type: 彩狗粮
  level: 96
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 调律材料/B714FB92.png
  type: 金狗粮
  level: 96
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 其他培养/EE48D579.png
  type: 装备碎片
  level: 91
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 调律材料/50540CAF.png
  type: 彩狗粮
  level: 91
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 调律材料/359DAAB4.png
  type: 金狗粮
  level: 91
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 其他培养/8FE34538.png
  type: ''
  level: null
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 培养定音/AC265AF8.png
  type: 止戈定音石
  level: 110
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 其他培养/11108830.png
  type: ''
  level: 110
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 培养定音/B3C4B1B1.png
  type: 定音石
  level: 110
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 其他培养/C52609C8.png
  type: 承音石
  level: 110
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 培养定音/3C3D6572.png
  type: 变音石
  level: 110
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/D793DA59.png
  type: 变音石
  level: 110
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/888F5D01.png
  type: 转律石
  level: 110
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 调律材料/01F4ECE6.png
  type: 紫狗粮
  level: 110
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 培养定音/C1192E1B.png
  type: 止戈定音石
  level: 105
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/BC4E5B74.png
  type: 定音石
  level: 105
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 其他培养/9C2ABA08.png
  type: ''
  level: 105
  group: 其他培养
  source: image_2.bmp
  notes: ''
- file: 培养定音/7AD55F9D.png
  type: 变音石
  level: 105
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/2EC8F816.png
  type: 转律石
  level: 105
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 调律材料/514EE359.png
  type: 紫狗粮
  level: 105
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 培养定音/FF288346.png
  type: 止戈定音石
  level: 100
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/2784DFC4.png
  type: 定音石
  level: 100
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/12ED66D8.png
  type: 传律石
  level: 100
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/C0B86A43.png
  type: 变音石
  level: 100
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 调律材料/C2AD77D2.png
  type: 紫狗粮
  level: 100
  group: 调律材料
  source: image_2.bmp
  notes: ''
- file: 培养定音/34D56A7E.png
  type: ''
  level: 96
  group: 培养定音
  source: image_2.bmp
  notes: ''
- file: 培养定音/9DC5DC65.png
  type: 定音石
  level: 96
  group: 培养定音
  source: image_2.bmp
  notes: ''
