version: 1
meta_schema:
- key: level
  name: 等级
  filterable: true
  type: number
  sort_by: desc
- key: count
  name: 数量
  filterable: false
  type: number
  sort_by: asc
references:
- file: 装备材料/475BF859.png
  label: 装备碎片
  meta:
    level: 110
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/D90CF5A6.png
  label: 彩狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/EC3D0E06.png
  label: 金狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备材料/DBFA2793.png
  label: 装备碎片
  meta:
    level: 105
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/F2130E50.png
  label: 彩狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/946CC90C.png
  label: 金狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备材料/24CCB99E.png
  label: 装备碎片
  meta:
    level: 100
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/7D3E1342.png
  label: 金狗粮
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备材料/28ED555E.png
  label: 装备碎片
  meta:
    level: 96
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/895530AE.png
  label: 彩狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/B72C379B.png
  label: 金狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备材料/5EE6F5A4.png
  label: 装备碎片
  meta:
    level: 91
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/DA54B4BF.png
  label: 彩狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/025FE7FC.png
  label: 金狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备材料/CD8CEA8A.png
  label: 装备碎片
  meta:
    level: 86
    group: 装备材料
  source: clipboard
  notes: ''
- file: 调律材料/0B20A87D.png
  label: 金狗粮
  meta:
    level: 86
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/E90F8B8F.png
  label: 彩狗粮
  meta:
    level: 81
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/B12F39AF.png
  label: 金狗粮
  meta:
    level: 81
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/5BB3DEEB.png
  label: 金狗粮
  meta:
    level: 71
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/39B2C751.png
  label: 金狗粮
  meta:
    level: 51
    group: 调律材料
  source: clipboard
  notes: ''
- file: 其他培养/C784A025.png
  label: 奇术丹
  meta:
    group: 其他培养
  source: clipboard
  notes: ''
- file: 定音转律/7CB8171A.png
  label: 止戈定音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/AA3BBF3B.png
  label: 啸玉
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/27B17F0B.png
  label: 定音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/EAD816D7.png
  label: 传律石
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: 装备培养/CF813DEE.png
  label: 承音石
  meta:
    level: 110
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/F476BC36.png
  label: 止戈变音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/5A8FEDD2.png
  label: 变音石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/4B117BB7.png
  label: 转律石
  meta:
    level: 110
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/9625FF60.png
  label: 紫狗粮
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/DEC6244A.png
  label: 止戈定音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/F3C84593.png
  label: 定音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/2ED12621.png
  label: 承音石
  meta:
    level: 105
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/7D7FF1CB.png
  label: 止戈变音石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/D753EFED.png
  label: 转律石
  meta:
    level: 105
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/AE8666A5.png
  label: 紫狗粮
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/E07396A6.png
  label: 止戈定音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/886B3F20.png
  label: 定音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/A775BBF0.png
  label: 传律石
  meta:
    level: 100
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/A5EE90AA.png
  label: 止戈变音石
  meta:
    level: 100
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/FFCBEA1D.png
  label: 紫狗粮
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/9547A900.png
  label: 止戈定音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/6C977B21.png
  label: 定音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/598D48C4.png
  label: 传律石
  meta:
    level: 96
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/B6F67472.png
  label: 止戈变音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/5CEA3A88.png
  label: 变音石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/4EA174CA.png
  label: 转律石
  meta:
    level: 96
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/4D4D9EDB.png
  label: 紫狗粮
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/C6F203B0.png
  label: 止戈定音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/1373075E.png
  label: 啸玉
  meta:
    level: 91
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/FAF61FB3.png
  label: 定音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/33DA4809.png
  label: 止戈变音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/F3FEFBF2.png
  label: 变音石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/794E7310.png
  label: 转律石
  meta:
    level: 91
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/B560FFAE.png
  label: 紫狗粮
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/2B787250.png
  label: 定音石
  meta:
    level: 86
    group: 定音转律
  source: clipboard
  notes: ''
- file: 装备培养/94AB92E9.png
  label: 啸玉
  meta:
    level: 86
    group: 装备培养
  source: clipboard
  notes: ''
- file: 定音转律/54290841.png
  label: 变音石
  meta:
    level: 86
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/064943B5.png
  label: 转律石
  meta:
    level: 86
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/9BE9F463.png
  label: 紫狗粮
  meta:
    level: 86
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/1FE6527B.png
  label: 变音石
  meta:
    level: 81
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/7D77B9D2.png
  label: 转律石
  meta:
    level: 81
    group: 定音转律
  source: clipboard
  notes: ''
- file: 定音转律/FD42CCB6.png
  label: 定音石
  meta:
    level: 61
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/45D8E60A.png
  label: 紫狗粮
  meta:
    level: 61
    group: 调律材料
  source: clipboard
  notes: ''
- file: 定音转律/688A96C4.png
  label: 定音石
  meta:
    level: 51
    group: 定音转律
  source: clipboard
  notes: ''
- file: 调律材料/26A86377.png
  label: 大律准石
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/188A0FD2.png
  label: 大律准石
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/AF43ACCC.png
  label: 大律准石
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/C4EB10EA.png
  label: 大律准石
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/E525FABE.png
  label: 大律准石
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/E2CB0994.png
  label: 大律准石
  meta:
    level: 86
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/1D6B1C00.png
  label: 大律准石
  meta:
    level: 81
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/3C7C4C01.png
  label: 大律准石
  meta:
    level: 71
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/5AFABDB7.png
  label: 大律准石
  meta:
    level: 61
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/C8FFCA19.png
  label: 大律准石
  meta:
    level: 56
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/F3768512.png
  label: 大律准石
  meta:
    level: 51
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备培养/8BF65636.png
  label: 溯玉
  meta:
    group: 装备培养
  source: clipboard
  notes: ''
- file: 调律材料/19C15875.png
  label: 律准石
  meta:
    group: 调律材料
  source: clipboard
  notes: ''
- file: 装备培养/A20C7B45.png
  label: 振玉
  meta:
    group: 装备培养
  source: clipboard
  notes: ''
- file: 调律材料/80CFEC02.png
  label: 小律准石
  meta:
    level: 110
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/587E0292.png
  label: 小律准石
  meta:
    level: 105
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/4476C8DE.png
  label: 小律准石
  meta:
    level: 100
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/010EE2DC.png
  label: 小律准石
  meta:
    level: 96
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/E5C29904.png
  label: 小律准石
  meta:
    level: 91
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/8D149098.png
  label: 小律准石
  meta:
    level: 86
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/161CF0A6.png
  label: 小律准石
  meta:
    level: 56
    group: 调律材料
  source: clipboard
  notes: ''
- file: 调律材料/685989EA.png
  label: 小律准石
  meta:
    level: 51
    group: 调律材料
  source: clipboard
  notes: ''
- file: 普通道具/6DAD5F1F.png
  label: 装备匣子
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/63BED34F.png
  label: 金装自选箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/BDE43720.png
  label: 自选词条优
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/5DC3A2EC.png
  label: 自选词条普
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/B8DE1C37.png
  label: 战令经验
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/9AB22E8A.png
  label: 金狗粮追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/C9789D43.png
  label: 定音石追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/A5736562.png
  label: 律准石追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/5AB120F5.png
  label: 金装追赶箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/5E61405F.png
  label: 短陌钱箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/A7BEE0D2.png
  label: 礼物盒
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/B21F3A19.png
  label: 材料箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/93885CB0.png
  label: 武学心得
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/22A110BD.png
  label: 武学突破箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/C3E428E6.png
  label: 武学升级箱
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/55F6B172.png
  label: 袅袅之音
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/204ECF64.png
  label: 八音窍
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/0269BEFC.png
  label: 绕梁之音
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/99588D75.png
  label: 袅袅非绑
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
- file: 普通道具/5C04CF08.png
  label: 折音券
  meta:
    group: 普通道具
  source: clipboard
  notes: ''
