schema_version: 2
scenes:
  general:
    name: 通用
    items:
    - game_main_page
    - game_menu_page
    - game_login_page
    - general_control
    - general_action
    - general_chat
    - general_purchase
  training:
    name: 培养
    items:
    - equip_detail
    - equip_weapon_detail
    - equip_armor_detail
    - equip_tune_detail
    - training_main
    - training_xinfa
    - role_detail
  resource:
    name: 物资
    items:
    - bag_detail
    - bag_equip_detail
    - bag_item_detail
    - bag_wallet_detail
    - bugan_detail
    - zhanling_detail
    - shop_detail
  social:
    name: 社交
    items:
    - school_main
    - baiye_main
    - waiguan_yigui
    - waiguan_qingjing
  activity:
    name: 活动
    items:
    - activity_main
    - activity_jianghu
    - activity_huoyun
    - activity_mengzhu
  component:
    name: 组件
    items:
    - jianghu_card
    - huoyun_card
