layout_scenes:
  group_1:
  - game_main_page
  - game_menu_page
  - general_control
  - general_action
  - game_login_page
  group_2:
  - equip_detail
  - equip_weapon_detail
  - equip_armor_detail
  - equip_tune_detail
  - training_main
  - training_xinfa
  - role_detail
  group_3:
  - bag_equip_detail
  - bag_item_detail
  - bag_wallet_detail
  group_6:
  - school_main
  - waiguan_yigui
  - waiguan_qingjing
  group_5:
  - activity_mengzhu
  - activity_jianghu
group_names:
  group_1: 通用
  group_2: 培养
  group_3: 背包
  group_6: 社交
  group_5: 活动
