base_attrs:
  main_weapon:
    _attr: 外功攻击
    _range: true
    110:
      gold:
        min: 100
        max: 232
      purple:
        min: 90
        max: 209
      blue:
        min: 80
        max: 186
    105:
      gold:
        min: 87
        max: 203
      purple:
        min: 79
        max: 183
      blue:
        min: 70
        max: 162
  sub_weapon:
    _follow: main_weapon
  ring:
    _attr: 最小外功攻击
    110:
      gold: 133
      purple: 120
      blue: 106
    105:
      gold: 116
      purple: 105
      blue: 93
  pendant:
    _attr: 最大外功攻击
    110:
      gold: 199
      purple: 179
      blue: 159
    105:
      gold: 174
      purple: 157
      blue: 139
  head:
    _attr: 气血最大值
    110:
      gold: 9723
      purple: 8750
      blue: 7778
    105:
      gold: 8225
      purple: 7402
      blue: 6580
  chest:
    _attr: 气血最大值
    110:
      gold: 19445
      purple: 17500
      blue: 15556
    105:
      gold: 16449
      purple: 14804
      blue: 13160
  leg:
    _follow: head
  wrist:
    _follow: head
affix_caps:
  外功攻击:
    _aliases:
    - 最大外功攻击
    - 最小外功攻击
    110:
      cap: 121.4
      unit: ''
    105:
      cap: 105.6
      unit: ''
  属性攻击:
    _aliases:
    - 最大无相攻击
    - 最小无相攻击
    - 最大牵丝攻击
    - 最小牵丝攻击
    - 最大鸣金攻击
    - 最小鸣金攻击
    - 最大裂石攻击
    - 最小裂石攻击
    - 最大破竹攻击
    - 最小破竹攻击
    110:
      cap: 68.8
      unit: ''
    105:
      cap: 59.8
      unit: ''
  五维属性:
    _aliases:
    - 劲
    - 势
    - 敏
    - 体
    - 御
    110:
      cap: 76.8
      unit: ''
    105:
      cap: 66.8
      unit: ''
  会意率:
    _aliases:
    - 会意率
    110:
      cap: 7
      unit: '%'
    105:
      cap: 6
      unit: '%'
  会心率:
    _aliases:
    - 会心率
    110:
      cap: 14
      unit: '%'
    105:
      cap: 12.2
      unit: '%'
  精准率:
    _aliases:
    - 精准率
    110:
      cap: 12.4
      unit: '%'
    105:
      cap: 10.8
      unit: '%'
  指定武学增效:
    _aliases:
    - 剑武学增伤
    - 枪武学增伤
    - 陌刀武学增伤
    - 唐横刀武学增伤
    - 扇武学增伤
    - 伞武学增伤
    - 舞绫鼓武学增伤
    - 双刀武学增伤
    - 绳镖武学增伤
    - 手甲武学增伤
    - 扇武学增效
    110:
      cap: 9.8
      unit: '%'
    105:
      cap: 8.6
      unit: '%'
  全部武学增效:
    _aliases:
    - 全武学增效
    110:
      cap: 4.9
      unit: '%'
    105:
      cap: 4.2
      unit: '%'
  对单位增效:
    _aliases:
    - 对首领单位增伤
    - 对玩家单位增效
    110:
      cap: 5.1
      unit: '%'
    105:
      cap: 4.4
      unit: '%'
  奇术类增伤:
    _aliases:
    - 单体类奇术增伤
    - 群体类奇术增伤
    110:
      cap: 15
      unit: '%'
    105:
      cap: 13.4
      unit: '%'
  气血最大值:
    _aliases:
    - 气血最大值
    110:
      cap: 4010
      unit: ''
  外功防御:
    _aliases:
    - 外功防御
    110:
      cap: 52.8
      unit: ''
  外功增益:
    _pool: dingyin
    _aliases:
    - 外功穿透
    - 外功抗性
    110:
      cap: 16.8
      unit: '%'
    105:
      cap: 14.6
      unit: '%'
  属攻增益:
    _pool: dingyin
    _aliases:
    - 属攻穿透
    110:
      cap: 20
      unit: '%'
    105:
      cap: 17.4
      unit: '%'
  指定技能增效:
    _pool: dingyin
    _aliases:
      鸣金·虹:
      - 无名剑法武学技增伤
      - 无名剑法蓄力技增伤
      - 无名剑法特殊技增伤
      - 无名枪法蓄力技增伤
      - 无名枪法特殊技增伤
      鸣金·影:
      - 积矩九剑武学技增伤
      - 积矩九剑特殊技增伤
      - 积矩九剑流血增伤
      - 九曲惊神枪武学技增伤
      - 九曲惊神枪蓄力技增伤
      裂石·威:
      - 嗟夫刀法护盾增效
      - 嗟夫刀法蓄力技增伤
      - 嗟夫刀法特殊技增伤
      - 八方风雷枪蓄力技增伤
      - 八方风雷枪特殊技增伤
      裂石·钧:
      - 斩雪刀法武学技增伤
      - 斩雪刀法蓄力技增伤
      - 斩雪刀法轻重击派生技增伤
      - 十方破阵武学技增伤
      - 十方破阵蓄力技增伤
      牵丝·玉:
      - 青山执笔蓄力技增伤
      - 青山执笔特殊及追击技增伤
      - 九重春色武学技增伤
      - 九重春色蓄力技增伤
      - 九重春色特殊技增伤
      - 九重春色高频弹道增伤
      - 九重春色轻重击及派生增伤
      牵丝·霖:
      - 明川药典武学技增疗
      - 明川药典特殊技增疗
      - 明川药典治疗技增疗
      - 千香引魂蛊武学技增疗
      - 千香引魂蛊特殊技增疗
      牵丝·翊:
      - 文动霓裳武学技增伤
      - 文动霓裳轻重击及派生增伤
      - 文动霓裳特殊技增伤
      - 杏游草野武学技增伤
      - 杏游草野重击及派生技增伤
      破竹·风:
      - 泥犁三垢武学技增伤
      - 泥犁三垢强效轻击增伤
      - 泥犁三垢特殊技增伤
      - 粟子游尘武学技增伤
      - 粟子游尘鼠鼠增伤
      破竹·尘:
      - 醉梦游春武学技增伤
      - 醉梦游春特殊技增伤
      - 粟子行云武学技增伤
      - 粟子行云蓄力技增伤
      - 粟子行云特殊技增伤
      破竹·鸢:
      - 天志垂象武学技增伤
      - 天志垂象蓄力技增伤
      - 天志垂象轻击及派生技增伤
      - 千机索天重击增伤
      - 千机索天特殊技增伤
    110:
      cap: 9.2
      unit: '%'
    105:
      cap: 8
      unit: '%'
