base_attrs:
  weapon:
    _attr: 外功攻击
    _range: true
    110:
      gold:
        min: 100
        max: 232
      purple:
        min: 90
        max: 209
      blue:
        min: 80
        max: 186
    105:
      gold:
        min: 87
        max: 203
      purple:
        min: 79
        max: 183
      blue:
        min: 70
        max: 162
    100:
      gold:
        min: 75
        max: 175
      purple:
        min: 68
        max: 158
      blue:
        min: 60
        max: 140
    96:
      gold:
        min: 65
        max: 151
      purple:
        min: 59
        max: 136
      blue:
        min: 52
        max: 121
  ring:
    _attr: 最小外功攻击
    110:
      gold: 133
      purple: 120
      blue: 106
    105:
      gold: 116
      purple: 105
      blue: 93
    100:
      gold: 100
      purple: 90
      blue: 80
    96:
      gold: 86
      purple: 78
      blue: 69
  pendant:
    _attr: 最大外功攻击
    110:
      gold: 199
      purple: 179
      blue: 159
    105:
      gold: 174
      purple: 157
      blue: 139
    100:
      gold: 150
      purple: 135
      blue: 120
    96:
      gold: 129
      purple: 116
      blue: 104
  head:
    _attr: 气血最大值
    110:
      gold: 9723
      purple: 8750
      blue: 7778
    105:
      gold: 8225
      purple: 7402
      blue: 6580
    100:
      gold: 6879
      purple: 6192
      blue: 5504
    96:
      gold: 5774
      purple: 5196
      blue: 4619
  chest:
    _attr: 气血最大值
    110:
      gold: 19445
      purple: 17500
      blue: 15556
    105:
      gold: 16449
      purple: 14804
      blue: 13160
    100:
      gold: 13758
      purple: 12383
      blue: 11007
    96:
      gold: 11547
      purple: 10392
      blue: 9238
  leg:
    _follow: head
  wrist:
    _follow: head
affix_caps:
  外功攻击:
    _aliases:
    - 最大外功攻击
    - 最小外功攻击
    110:
      cap: 121.4
    105:
      cap: 105.6
    100:
      cap: 90.6
  属性攻击:
    _group: true
    _aliases:
      通用:
      - 最大无相攻击
      - 最小无相攻击
      鸣金:
      - 最大鸣金攻击
      - 最小鸣金攻击
      牵丝:
      - 最大牵丝攻击
      - 最小牵丝攻击
      裂石:
      - 最大裂石攻击
      - 最小裂石攻击
      破竹:
      - 最大破竹攻击
      - 最小破竹攻击
    110:
      cap: 68.8
    105:
      cap: 59.8
    100:
      cap: 51.4
  五维属性:
    _aliases:
    - 劲
    - 势
    - 敏
    - 体
    - 御
    110:
      cap: 76.8
    105:
      cap: 66.8
    100:
      cap: 57.4
  会意率:
    _unit: '%'
    _aliases:
    - 会意率
    110:
      cap: 7
    105:
      cap: 6
    100:
      cap: 5.2
  会心率:
    _unit: '%'
    _aliases:
    - 会心率
    110:
      cap: 14
    105:
      cap: 12.2
    100:
      cap: 10.4
  精准率:
    _unit: '%'
    _aliases:
    - 精准率
    110:
      cap: 12.4
    105:
      cap: 10.8
    100:
      cap: 9.2
  指定武学增效:
    _unit: '%'
    _aliases:
    - 剑武学增伤
    - 枪武学增伤
    - 陌刀武学增伤
    - 横刀武学增伤
    - 伞武学增效
    - 舞绫鼓武学增伤
    - 双刀武学增伤
    - 绳镖武学增伤
    - 手甲武学增伤
    - 扇武学增效
    110:
      cap: 9.8
    105:
      cap: 8.6
  全部武学增效:
    _unit: '%'
    _aliases:
    - 全武学增效
    110:
      cap: 4.9
    105:
      cap: 4.2
  对单位增效:
    _unit: '%'
    _aliases:
    - 对首领单位增伤
    - 对玩家单位增效
    110:
      cap: 5.1
    105:
      cap: 4.4
  奇术类增伤:
    _unit: '%'
    _aliases:
    - 单体类奇术增伤
    - 群体类奇术增伤
    110:
      cap: 15
    105:
      cap: 13.4
  气血最大值:
    _aliases:
    - 气血最大值
    110:
      cap: 4010
  外功防御:
    _aliases:
    - 外功防御
    110:
      cap: 52.8
  外功增益:
    _pool: dingyin
    _unit: '%'
    _aliases:
    - 外功穿透
    - 外功抗性
    110:
      cap: 16.8
    105:
      cap: 14.6
  属攻增益:
    _pool: dingyin
    _unit: '%'
    _aliases:
    - 无相穿透
    110:
      cap: 20
    105:
      cap: 17.4
    100:
      cap: 15.2
  指定技能增效:
    _pool: dingyin
    _group: true
    _unit: '%'
    _aliases:
      鸣金·虹:
      - 无名剑法武学技增伤
      - 无名剑法蓄力技增伤
      - 无名剑法特殊技增伤
      - 无名枪法蓄力技增伤
      - 无名枪法特殊技增伤
      鸣金·影:
      - 积矩九剑武学技增伤
      - 积矩九剑特殊技增伤
      - 积矩九剑流血增伤
      - 九曲惊神枪武学技增伤
      - 九曲惊神枪蓄力技增伤
      裂石·威:
      - 嗟夫刀法护盾增效
      - 嗟夫刀法蓄力技增伤
      - 嗟夫刀法特殊技增伤
      - 八方风雷枪蓄力技增伤
      - 八方风雷枪特殊技增伤
      裂石·钧:
      - 斩雪刀法武学技增伤
      - 斩雪刀法蓄力技增伤
      - 斩雪刀法轻重击派生技增伤
      - 十方破阵武学技增伤
      - 十方破阵蓄力技增伤
      牵丝·玉:
      - 青山执笔蓄力技增伤
      - 青山执笔特殊及追击技增伤
      - 九重春色武学技增伤
      - 九重春色蓄力技增伤
      - 九重春色特殊技增伤
      - 九重春色高频弹道增伤
      - 九重春色轻重击及派生增伤
      牵丝·霖:
      - 明川药典武学技增疗
      - 明川药典特殊技增疗
      - 明川药典治疗技增疗
      - 千香引魂蛊武学技增疗
      - 千香引魂蛊特殊技增疗
      牵丝·翊:
      - 文动霓裳武学技增伤
      - 文动霓裳轻重击及派生增伤
      - 文动霓裳特殊技增伤
      - 杏游草野武学技增伤
      - 杏游草野重击及派生技增伤
      破竹·风:
      - 泥犁三垢武学技增伤
      - 泥犁三垢强效轻击增伤
      - 泥犁三垢特殊技增伤
      - 粟子游尘武学技增伤
      - 粟子游尘鼠鼠增伤
      破竹·尘:
      - 醉梦游春武学技增伤
      - 醉梦游春特殊技增伤
      - 粟子行云武学技增伤
      - 粟子行云蓄力技增伤
      - 粟子行云特殊技增伤
      破竹·鸢:
      - 天志垂象武学技增伤
      - 天志垂象蓄力技增伤
      - 天志垂象轻击及派生技增伤
      - 千机索天重击增伤
      - 千机索天特殊技增伤
    110:
      cap: 9.2
    105:
      cap: 8
    100:
      cap: 7
affix_categories:
  外功类:
  - 最大外功攻击
  - 最小外功攻击
  - 劲
  - 势
  - 敏
  属攻类:
  - 最大无相攻击
  - 最小无相攻击
  - 最大鸣金攻击
  - 最小鸣金攻击
  - 最大牵丝攻击
  - 最小牵丝攻击
  - 最大裂石攻击
  - 最小裂石攻击
  - 最大破竹攻击
  - 最小破竹攻击
  三率类:
  - 会意率
  - 会心率
  - 精准率
  增效类:
  - 全武学增效
  - 对首领单位增伤
  - 对玩家单位增效
  - 单体类奇术增伤
  - 群体类奇术增伤
  武器类:
  - 剑武学增伤
  - 枪武学增伤
  - 陌刀武学增伤
  - 横刀武学增伤
  - 伞武学增效
  - 舞绫鼓武学增伤
  - 绳镖武学增伤
  - 手甲武学增伤
  - 扇武学增效
  - 双刀武学增伤
  生存类:
  - 体
  - 御
  - 气血最大值
  - 外功防御
weapon_types:
- name: 剑
  wuxue_affix: 剑武学增伤
- name: 枪
  wuxue_affix: 枪武学增伤
- name: 伞
  wuxue_affix: 伞武学增效
- name: 扇
  wuxue_affix: 扇武学增效
- name: 陌刀
  wuxue_affix: 陌刀武学增伤
- name: 双刀
  wuxue_affix: 双刀武学增伤
- name: 绳镖
  wuxue_affix: 绳镖武学增伤
- name: 横刀
  wuxue_affix: 横刀武学增伤
- name: 手甲
  wuxue_affix: 手甲武学增伤
- name: 舞绫鼓
  wuxue_affix: 舞绫鼓武学增伤
schools:
  鸣金·虹:
    attr: 鸣金
    main:
      weapon: 剑
      martial_art: 无名剑法
    sub:
      weapon: 枪
      martial_art: 无名枪法
  鸣金·影:
    attr: 鸣金
    main:
      weapon: 剑
      martial_art: 积矩九剑
    sub:
      weapon: 枪
      martial_art: 九曲惊神枪
  裂石·威:
    attr: 裂石
    main:
      weapon: 陌刀
      martial_art: 嗟夫刀法
    sub:
      weapon: 枪
      martial_art: 八方风雷枪
  裂石·钧:
    attr: 裂石
    main:
      weapon: 横刀
      martial_art: 斩雪刀法
    sub:
      weapon: 陌刀
      martial_art: 十方破阵
  牵丝·玉:
    attr: 牵丝
    main:
      weapon: 伞
      martial_art: 九重春色
    sub:
      weapon: 扇
      martial_art: 青山执笔
  牵丝·霖:
    attr: 牵丝
    main:
      weapon: 扇
      martial_art: 明川药典
    sub:
      weapon: 伞
      martial_art: 千香引魂蛊
  牵丝·翊:
    attr: 牵丝
    main:
      weapon: 舞绫鼓
      martial_art: 文动霓裳
    sub:
      weapon: 扇
      martial_art: 杏游草野
  破竹·风:
    attr: 破竹
    main:
      weapon: 双刀
      martial_art: 泥犁三垢
    sub:
      weapon: 绳镖
      martial_art: 粟子游尘
  破竹·尘:
    attr: 破竹
    main:
      weapon: 伞
      martial_art: 醉梦游春
    sub:
      weapon: 绳镖
      martial_art: 粟子行云
  破竹·鸢:
    attr: 破竹
    main:
      weapon: 手甲
      martial_art: 天志垂象
    sub:
      weapon: 绳镖
      martial_art: 千机索天
  破竹·樽:
    attr: 破竹
    main:
      weapon: 手甲
      martial_art: 悬身拳法
    sub:
      weapon: 双刀
      martial_art: 断水双诀
affix_parts:
  最大无相攻击:
  - 武器
  最小无相攻击:
  - 武器
  最大鸣金攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小鸣金攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大牵丝攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大裂石攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大破竹攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小破竹攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小裂石攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小牵丝攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  全武学增效:
  - 环
  - 佩
  对首领单位增伤:
  - 胫甲
  - 腕甲
  对玩家单位增效:
  - 胫甲
  - 腕甲
  单体类奇术增伤:
  - 冠胄
  - 胸甲
  群体类奇术增伤:
  - 冠胄
  - 胸甲
  剑武学增伤:
  - 武器
  枪武学增伤:
  - 武器
  陌刀武学增伤:
  - 武器
  横刀武学增伤:
  - 武器
  伞武学增效:
  - 武器
  舞绫鼓武学增伤:
  - 武器
  双刀武学增伤:
  - 武器
  绳镖武学增伤:
  - 武器
  手甲武学增伤:
  - 武器
  扇武学增效:
  - 武器
level_configs:
- level: 91
  allow_reset: false
  judge_resistance: 45
- level: 96
  allow_reset: false
  judge_resistance: 65
- level: 100
  allow_reset: true
  min_material_count: 1
  judge_resistance: 85
- level: 105
  allow_reset: true
  min_material_count: 2
  judge_resistance: 115
- level: 110
  allow_reset: true
  min_material_count: 2
  judge_resistance: 145
  buff_resistance: 15
season_configs:
- season_number: 1
  name: 蕤宾叠奏
  start_date: '2026-06-26'
  end_date: '2026-09-24'
  first_half_end_date: '2026-08-07'
  equip_level: 110
