base_attrs:
  weapon:
    _attr: 外功攻击
    _range: true
    110:
      gold:
        min: 100
        max: 232
      purple:
        min: 90
        max: 209
      blue:
        min: 80
        max: 186
    105:
      gold:
        min: 87
        max: 203
      purple:
        min: 79
        max: 183
      blue:
        min: 70
        max: 162
    100:
      gold:
        min: 75
        max: 175
      purple:
        min: 68
        max: 158
      blue:
        min: 60
        max: 140
    96:
      gold:
        min: 65
        max: 151
      purple:
        min: 59
        max: 136
      blue:
        min: 52
        max: 121
    _first_affixes:
    - 最大外功攻击
    - 最小外功攻击
    - 势
    - 敏
    - 最大无相攻击
    - 最小无相攻击
  ring:
    _name_suffixes:
    - 云珑
    _type_aliases:
    - 环
    _attr: 最小外功攻击
    110:
      gold: 133
      purple: 120
      blue: 106
    105:
      gold: 116
      purple: 105
      blue: 93
    100:
      gold: 100
      purple: 90
      blue: 80
    96:
      gold: 86
      purple: 78
      blue: 69
    _first_affixes:
    - 最大外功攻击
    - 最小外功攻击
  pendant:
    _name_suffixes:
    - 辟邪
    _type_aliases:
    - 佩
    _attr: 最大外功攻击
    110:
      gold: 199
      purple: 179
      blue: 159
    105:
      gold: 174
      purple: 157
      blue: 139
    100:
      gold: 150
      purple: 135
      blue: 120
    96:
      gold: 129
      purple: 116
      blue: 104
    _first_affixes:
    - 最大外功攻击
    - 最小外功攻击
  head:
    _name_suffixes:
    - 冠
    _type_aliases:
    - 冠胄
    - 冠
    - 胄
    _attr: 气血最大值
    110:
      gold: 9723
      purple: 8750
      blue: 7778
    105:
      gold: 8225
      purple: 7402
      blue: 6580
    100:
      gold: 6879
      purple: 6192
      blue: 5504
    96:
      gold: 5774
      purple: 5196
      blue: 4619
    _first_affixes:
    - 精准率
    - 会心率
    - 会意率
    - 外功防御
    - 气血最大值
  chest:
    _name_suffixes:
    - 甲
    _type_aliases:
    - 胸甲
    - 胸
    _attr: 气血最大值
    110:
      gold: 19445
      purple: 17500
      blue: 15556
    105:
      gold: 16449
      purple: 14804
      blue: 13160
    100:
      gold: 13758
      purple: 12383
      blue: 11007
    96:
      gold: 11547
      purple: 10392
      blue: 9238
    _first_affixes:
    - 精准率
    - 会心率
    - 会意率
    - 外功防御
    - 气血最大值
  leg:
    _name_suffixes:
    - 缚袴
    - 缚
    _type_aliases:
    - 胫甲
    _follow: head
    _first_affixes:
    - 劲
    - 精准率
    - 会心率
    - 会意率
    - 体
    - 外功防御
    - 气血最大值
  wrist:
    _name_suffixes:
    - 披膊
    _type_aliases:
    - 腕甲
    _follow: head
    _first_affixes:
    - 劲
    - 精准率
    - 会心率
    - 会意率
    - 体
    - 外功防御
    - 气血最大值
affix_caps:
  外功攻击:
    _aliases:
    - 最大外功攻击
    - 最小外功攻击
    110:
      cap: 121.4
    105:
      cap: 105.6
    100:
      cap: 90.6
  属性攻击:
    _group: true
    _aliases:
      通用:
      - 最大无相攻击
      - 最小无相攻击
      鸣金:
      - 最大鸣金攻击
      - 最小鸣金攻击
      牵丝:
      - 最大牵丝攻击
      - 最小牵丝攻击
      裂石:
      - 最大裂石攻击
      - 最小裂石攻击
      破竹:
      - 最大破竹攻击
      - 最小破竹攻击
    110:
      cap: 68.8
    105:
      cap: 59.8
    100:
      cap: 51.4
  五维属性:
    _aliases:
    - 劲
    - 势
    - 敏
    - 体
    - 御
    110:
      cap: 76.8
    105:
      cap: 66.8
    100:
      cap: 57.4
  会意率:
    _unit: '%'
    _aliases:
    - 会意率
    110:
      cap: 7
    105:
      cap: 6
    100:
      cap: 5.2
  会心率:
    _unit: '%'
    _aliases:
    - 会心率
    110:
      cap: 14
    105:
      cap: 12.2
    100:
      cap: 10.4
  精准率:
    _unit: '%'
    _aliases:
    - 精准率
    110:
      cap: 12.4
    105:
      cap: 10.8
    100:
      cap: 9.4
  指定武学增效:
    _unit: '%'
    _aliases:
    - 剑武学增伤
    - 枪武学增伤
    - 陌刀武学增伤
    - 横刀武学增伤
    - 伞武学增效
    - 舞绫鼓武学增伤
    - 双刀武学增伤
    - 绳镖武学增伤
    - 手甲武学增伤
    - 扇武学增效
    110:
      cap: 9.8
    105:
      cap: 8.6
  全部武学增效:
    _unit: '%'
    _aliases:
    - 全武学增效
    110:
      cap: 4.9
    105:
      cap: 4.2
  对单位增效:
    _unit: '%'
    _aliases:
    - 对首领单位增伤
    - 对玩家单位增效
    110:
      cap: 5.1
    105:
      cap: 4.4
  奇术类增伤:
    _unit: '%'
    _aliases:
    - 单体类奇术增伤
    - 群体类奇术增伤
    110:
      cap: 15.4
    105:
      cap: 13.4
  气血最大值:
    _aliases:
    - 气血最大值
    110:
      cap: 4610
    105:
      cap: 4010
  外功防御:
    _aliases:
    - 外功防御
    110:
      cap: 60.6
    105:
      cap: 52.8
  外功增益:
    _pool: dingyin
    _unit: '%'
    _parts:
    - 武器
    - 环
    - 佩
    _aliases:
    - 外功穿透
    - 外功抗性
    110:
      cap: 16.8
    105:
      cap: 14.6
    100:
      cap: 12.8
  属攻增益:
    _pool: dingyin
    _unit: '%'
    _parts:
    - 武器
    - 环
    - 佩
    _aliases:
    - 无相穿透
    110:
      cap: 20
    105:
      cap: 17.4
    100:
      cap: 15.2
  指定技能增效:
    _pool: dingyin
    _group: true
    _unit: '%'
    _parts:
    - 冠胄
    - 胸甲
    - 胫甲
    - 腕甲
    _aliases:
      鸣金·虹:
      - 无名剑法武学技增伤
      - 无名剑法蓄力技增伤
      - 无名剑法特殊技增伤
      - 无名枪法蓄力技增伤
      - 无名枪法特殊技增伤
      鸣金·影:
      - 积矩九剑武学技增伤
      - 积矩九剑特殊技增伤
      - 积矩九剑流血增伤
      - 九曲惊神枪武学技增伤
      - 九曲惊神枪蓄力技增伤
      裂石·威:
      - 嗟夫刀法护盾增效
      - 嗟夫刀法蓄力技增伤
      - 嗟夫刀法特殊技增伤
      - 八方风雷枪蓄力技增伤
      - 八方风雷枪特殊技增伤
      裂石·钧:
      - 斩雪刀法武学技增伤
      - 斩雪刀法蓄力技增伤
      - 斩雪刀法轻重击派生技增伤
      - 十方破阵武学技增伤
      - 十方破阵蓄力技增伤
      牵丝·玉:
      - 青山执笔蓄力技增伤
      - 青山执笔特殊及追击技增伤
      - 九重春色武学技增伤
      - 九重春色蓄力技增伤
      - 九重春色特殊技增伤
      - 九重春色高频弹道增伤
      - 九重春色轻重击及派生增伤
      牵丝·霖:
      - 明川药典武学技增疗
      - 明川药典特殊技增疗
      - 明川药典治疗技增疗
      - 千香引魂蛊武学技增疗
      - 千香引魂蛊特殊技增疗
      牵丝·翊:
      - 文动霓裳武学技增伤
      - 文动霓裳轻重击及派生增伤
      - 文动霓裳特殊技增伤
      - 杏游草野武学技增伤
      - 杏游草野重击及派生技增伤
      破竹·风:
      - 泥犁三垢武学技增伤
      - 泥犁三垢强效轻击增伤
      - 泥犁三垢特殊技增伤
      - 粟子游尘武学技增伤
      - 粟子游尘鼠鼠增伤
      破竹·尘:
      - 醉梦游春武学技增伤
      - 醉梦游春特殊技增伤
      - 粟子行云武学技增伤
      - 粟子行云蓄力技增伤
      - 粟子行云特殊技增伤
      破竹·鸢:
      - 天志垂象武学技增伤
      - 天志垂象蓄力技增伤
      - 天志垂象轻击及派生技增伤
      - 千机索天重击增伤
      - 千机索天特殊技增伤
      破竹·樽:
      - 悬身断水·浓醺技能增伤
      - 断水双诀·轻击增伤
      - 悬身拳法·特殊技增伤
      - 断水双诀·武学技增伤
      - 悬身拳法·武学技增伤
    110:
      cap: 9.2
    105:
      cap: 8
    100:
      cap: 7
affix_categories:
  外功类:
  - 最大外功攻击
  - 最小外功攻击
  - 劲
  - 势
  - 敏
  属攻类:
  - 最大无相攻击
  - 最小无相攻击
  - 最大鸣金攻击
  - 最小鸣金攻击
  - 最大牵丝攻击
  - 最小牵丝攻击
  - 最大裂石攻击
  - 最小裂石攻击
  - 最大破竹攻击
  - 最小破竹攻击
  三率类:
  - 会意率
  - 会心率
  - 精准率
  增效类:
  - 全武学增效
  - 对首领单位增伤
  - 对玩家单位增效
  - 单体类奇术增伤
  - 群体类奇术增伤
  武器类:
  - 剑武学增伤
  - 枪武学增伤
  - 陌刀武学增伤
  - 横刀武学增伤
  - 伞武学增效
  - 舞绫鼓武学增伤
  - 绳镖武学增伤
  - 手甲武学增伤
  - 扇武学增效
  - 双刀武学增伤
  生存类:
  - 体
  - 御
  - 气血最大值
  - 外功防御
equipment_name_series:
  output:
    110: 流星
    105: 踏雪
    100: 绝尘
    96: 惊沙
    91: 飞将
  armor:
    110: 吴钩
    105: 雁南飞
    100: 万仞山
    96: 陇上
    91: 夜征人
weapon_types:
- name: 剑
  wuxue_affix: 剑武学增伤
  name_suffixes:
  - 含光
  type_aliases:
  - 剑
- name: 枪
  wuxue_affix: 枪武学增伤
  name_suffixes:
  - 羽林
  type_aliases:
  - 枪
- name: 伞
  wuxue_affix: 伞武学增效
  type_aliases:
  - 伞
  name_suffixes:
  - 云伞
- name: 扇
  wuxue_affix: 扇武学增效
  type_aliases:
  - 扇
  name_suffixes:
  - 画扇
- name: 陌刀
  wuxue_affix: 陌刀武学增伤
  type_aliases:
  - 陌刀
  name_suffixes:
  - 碎刃
- name: 双刀
  wuxue_affix: 双刀武学增伤
  type_aliases:
  - 双刀
  name_suffixes:
  - 双鲤
- name: 绳镖
  wuxue_affix: 绳镖武学增伤
  type_aliases:
  - 绳镖
  name_suffixes:
  - 鸣镖
- name: 横刀
  wuxue_affix: 横刀武学增伤
  type_aliases:
  - 横刀
  name_suffixes:
  - 断水
- name: 手甲
  wuxue_affix: 手甲武学增伤
  type_aliases:
  - 手甲
  name_suffixes:
  - 动岳
- name: 舞绫鼓
  wuxue_affix: 舞绫鼓武学增伤
  type_aliases:
  - 舞绫鼓
  - 鼓
  name_suffixes:
  - 凌波
martial_arts:
- name: 九重春色
  weapon: 伞
  attr: 牵丝
- name: 千香引魂蛊
  weapon: 伞
  attr: 牵丝
- name: 明川药典
  weapon: 扇
  attr: 牵丝
- name: 杏游草野
  weapon: 扇
  attr: 牵丝
- name: 青山执笔
  weapon: 扇
  attr: 牵丝
- name: 文动霓裳
  weapon: 舞绫鼓
  attr: 牵丝
- name: 醉梦游春
  weapon: 伞
  attr: 破竹
- name: 断水双诀
  weapon: 双刀
  attr: 破竹
- name: 泥犁三垢
  weapon: 双刀
  attr: 破竹
- name: 天志垂象
  weapon: 手甲
  attr: 破竹
- name: 悬身拳法
  weapon: 手甲
  attr: 破竹
- name: 千机索天
  weapon: 绳镖
  attr: 破竹
- name: 粟子游尘
  weapon: 绳镖
  attr: 破竹
- name: 粟子行云
  weapon: 绳镖
  attr: 破竹
- name: 八方风雷枪
  weapon: 枪
  attr: 裂石
- name: 斩雪刀法
  weapon: 横刀
  attr: 裂石
- name: 十方破阵
  weapon: 陌刀
  attr: 裂石
- name: 嗟夫刀法
  weapon: 陌刀
  attr: 裂石
- name: 无名剑法
  weapon: 剑
  attr: 鸣金
- name: 积矩九剑
  weapon: 剑
  attr: 鸣金
- name: 九曲惊神枪
  weapon: 枪
  attr: 鸣金
- name: 无名枪法
  weapon: 枪
  attr: 鸣金
playstyles:
- name: 火拳
  school: 牵丝·霖
  attr: 牵丝
  arts:
  - 明川药典
  - 千香引魂蛊
  main_weapon: 扇
  sub_weapon: 伞
  output_dingyin: 外功穿透
  defense_dingyin: ''
  main_damage: ''
  sub_damage: ''
  all_skill_requirement: 不需要
  qishu_requirement: 单体
  unit_requirement: 首领
- name: 纯奶
  school: 牵丝·霖
  attr: 牵丝
  arts:
  - 明川药典
  - 千香引魂蛊
  main_weapon: 扇
  main_damage: 扇武学增效
  sub_weapon: 伞
  output_dingyin: 外功穿透
  defense_dingyin: 明川药典治疗技增疗
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 玩家
- name: 纯唐
  school: 裂石·钧
  attr: 裂石
  arts:
  - 斩雪刀法
  - 十方破阵
  main_weapon: 横刀
  main_damage: 横刀武学增伤
  sub_weapon: 陌刀
  output_dingyin: 外功穿透
  defense_dingyin: 斩雪刀法轻重击派生技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 双切
  school: 裂石·钧
  attr: 裂石
  arts:
  - 斩雪刀法
  - 十方破阵
  main_weapon: 横刀
  main_damage: ''
  sub_weapon: 陌刀
  sub_damage: 陌刀武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 十方破阵蓄力技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 威威
  school: 裂石·威
  attr: 裂石
  arts:
  - 嗟夫刀法
  - 八方风雷枪
  main_weapon: 陌刀
  main_damage: 陌刀武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 嗟夫刀法蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 鸢鸢
  school: 破竹·鸢
  attr: 破竹
  arts:
  - 天志垂象
  - 千机索天
  main_weapon: 手甲
  main_damage: 手甲武学增伤
  sub_weapon: 绳镖
  output_dingyin: 外功穿透
  defense_dingyin: 天志垂象蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 双刀
  school: 破竹·风
  attr: 破竹
  arts:
  - 泥犁三垢
  - 粟子游尘
  main_weapon: 双刀
  main_damage: 双刀武学增伤
  sub_weapon: 绳镖
  sub_damage: 绳镖武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 粟子游尘鼠鼠增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 尘尘
  school: 破竹·尘
  attr: 破竹
  arts:
  - 醉梦游春
  - 粟子行云
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 绳镖
  output_dingyin: 外功穿透
  defense_dingyin: 醉梦游春武学技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
  sub_damage: ''
- name: 翊翊
  school: 牵丝·翊
  attr: 牵丝
  arts:
  - 文动霓裳
  - 杏游草野
  main_weapon: 舞绫鼓
  main_damage: 舞绫鼓武学增伤
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 文动霓裳特殊技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
  sub_damage: ''
- name: 樽樽
  school: 破竹·樽
  attr: 破竹
  arts:
  - 悬身拳法
  - 断水双诀
  main_weapon: 手甲
  main_damage: 手甲武学增伤
  sub_weapon: 双刀
  sub_damage: 双刀武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 悬身断水·浓醺技能增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 走地玉
  school: 牵丝·玉
  attr: 牵丝
  arts:
  - 九重春色
  - 青山执笔
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 九重春色高频弹道增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 单体
  unit_requirement: 首领
- name: 飞天玉
  school: 牵丝·玉
  attr: 牵丝
  arts:
  - 九重春色
  - 青山执笔
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 九重春色高频弹道增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 无名
  school: 鸣金·虹
  attr: 鸣金
  arts:
  - 无名剑法
  - 无名枪法
  main_weapon: 剑
  main_damage: 剑武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 无名剑法蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 九剑
  school: 鸣金·影
  attr: 鸣金
  arts:
  - 积矩九剑
  - 九曲惊神枪
  main_weapon: 剑
  main_damage: 剑武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 积矩九剑流血增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 单体
  unit_requirement: 首领
schools:
  鸣金·虹:
    schemes:
    - 基础方案
    attr: 鸣金
    main:
      weapon: 剑
      martial_art: 无名剑法
    sub:
      weapon: 枪
      martial_art: 无名枪法
  鸣金·影:
    schemes:
    - 基础方案
    attr: 鸣金
    main:
      weapon: 剑
      martial_art: 积矩九剑
    sub:
      weapon: 枪
      martial_art: 九曲惊神枪
  裂石·威:
    schemes:
    - 基础方案
    attr: 裂石
    main:
      weapon: 陌刀
      martial_art: 嗟夫刀法
    sub:
      weapon: 枪
      martial_art: 八方风雷枪
  裂石·钧:
    schemes:
    - 基础方案
    attr: 裂石
    main:
      weapon: 横刀
      martial_art: 斩雪刀法
    sub:
      weapon: 陌刀
      martial_art: 十方破阵
  牵丝·玉:
    schemes:
    - 基础方案
    attr: 牵丝
    main:
      weapon: 伞
      martial_art: 九重春色
    sub:
      weapon: 扇
      martial_art: 青山执笔
  牵丝·霖:
    schemes:
    - 基础方案
    attr: 牵丝
    main:
      weapon: 扇
      martial_art: 明川药典
    sub:
      weapon: 伞
      martial_art: 千香引魂蛊
  牵丝·翊:
    schemes:
    - 基础方案
    attr: 牵丝
    main:
      martial_art: 文动霓裳
      weapon: 舞绫鼓
    sub:
      martial_art: 杏游草野
      weapon: 扇
  破竹·风:
    schemes:
    - 基础方案
    attr: 破竹
    main:
      weapon: 双刀
      martial_art: 泥犁三垢
    sub:
      weapon: 绳镖
      martial_art: 粟子游尘
  破竹·尘:
    schemes:
    - 基础方案
    attr: 破竹
    main:
      weapon: 伞
      martial_art: 醉梦游春
    sub:
      weapon: 绳镖
      martial_art: 粟子行云
  破竹·鸢:
    schemes:
    - 基础方案
    attr: 破竹
    main:
      weapon: 手甲
      martial_art: 天志垂象
    sub:
      weapon: 绳镖
      martial_art: 千机索天
  破竹·樽:
    schemes:
    - 基础方案
    attr: 破竹
    main:
      weapon: 手甲
      martial_art: 悬身拳法
    sub:
      weapon: 双刀
      martial_art: 断水双诀
affix_aliases:
  全武学增效:
  - 全武增
  对首领单位增伤:
  - 首领增
  单体类奇术增伤:
  - 单体奇术增
  群体类奇术增伤:
  - 群体奇术增
  剑武学增伤:
  - 剑增
  枪武学增伤:
  - 枪增
  伞武学增效:
  - 伞增
  扇武学增效:
  - 扇增
  陌刀武学增伤:
  - 陌刀增
  双刀武学增伤:
  - 双刀增
  绳镖武学增伤:
  - 绳镖增
  横刀武学增伤:
  - 横刀增
  手甲武学增伤:
  - 拳甲增
  舞绫鼓武学增伤:
  - 鼓增
  无名剑法蓄力技增伤:
  - 蓄力技定音
  积矩九剑流血增伤:
  - 流血定音
  嗟夫刀法蓄力技增伤:
  - 蓄力技定音
  十方破阵蓄力技增伤:
  - 蓄力技定音
  九重春色高频弹道增伤:
  - 弹道定音
  文动霓裳特殊技增伤:
  - 特殊技定音
  泥犁三垢强效轻击增伤:
  - 轻击定音
  天志垂象蓄力技增伤:
  - 蓄力技定音
  悬身断水·浓醺技能增伤:
  - 酩酊技定音
  对玩家单位增效:
  - 玩家增
  醉梦游春武学技增伤:
  - 回旋伞定音
  粟子游尘鼠鼠增伤:
  - 老鼠定音
affix_parts:
  最大无相攻击:
  - 武器
  最小无相攻击:
  - 武器
  最大鸣金攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小鸣金攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大牵丝攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大裂石攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最大破竹攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小破竹攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小裂石攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  最小牵丝攻击:
  - 环
  - 佩
  - 冠胄
  - 胸甲
  - 胫甲
  - 腕甲
  全武学增效:
  - 环
  - 佩
  对首领单位增伤:
  - 胫甲
  - 腕甲
  对玩家单位增效:
  - 胫甲
  - 腕甲
  单体类奇术增伤:
  - 冠胄
  - 胸甲
  群体类奇术增伤:
  - 冠胄
  - 胸甲
  剑武学增伤:
  - 武器
  枪武学增伤:
  - 武器
  陌刀武学增伤:
  - 武器
  横刀武学增伤:
  - 武器
  伞武学增效:
  - 武器
  舞绫鼓武学增伤:
  - 武器
  双刀武学增伤:
  - 武器
  绳镖武学增伤:
  - 武器
  手甲武学增伤:
  - 武器
  扇武学增效:
  - 武器
level_configs:
- level: 91
  allow_reset: false
  allow_chengyin: true
  allow_retransfer: false
  judge_resistance: 45
- level: 96
  allow_reset: false
  allow_chengyin: true
  allow_retransfer: false
  judge_resistance: 65
- level: 100
  allow_reset: true
  allow_chengyin: true
  allow_retransfer: false
  min_material_count: 1
  judge_resistance: 85
- level: 105
  allow_reset: true
  allow_chengyin: true
  allow_retransfer: true
  min_material_count: 2
  judge_resistance: 115
- level: 110
  allow_reset: true
  allow_chengyin: true
  allow_retransfer: true
  allow_retransfer_after_chengyin: true
  min_material_count: 2
  judge_resistance: 145
  buff_resistance: 15
season_configs:
- season_number: 1
  name: 蕤宾叠奏
  start_date: '2026-06-26'
  end_date: '2026-09-24'
  first_half_end_date: '2026-08-07'
  equip_level: 110
