quality_thresholds:
  武器:
  - gold
  环:
  - gold
  佩:
  - gold
  冠胄:
  - gold
  - purple
  胸甲:
  - gold
  - purple
  胫甲:
  - gold
  - purple
  腕甲:
  - gold
  - purple
switches:
  keep_pvp:
    name: 保留PVP装备
materials:
  stone_check:
    enabled: false
    min_count: 80
  food_rules:
  - pct: 98
    min_expect: top
    min_quality: gold
    food: 彩狗粮
    on_insufficient: skip
  - pct: 88
    min_expect: excellent
    min_quality: gold
    food: 金狗粮
    on_insufficient: skip
  - pct: 0
    min_expect: normal
    min_quality: gold
    food: ''
    on_insufficient: continue
  - pct: 92
    min_expect: top
    min_quality: purple
    food: 金狗粮
    on_insufficient: skip
  - pct: 0
    min_expect: excellent
    min_quality: purple
    food: 紫狗粮
    on_insufficient: continue
behavior:
  scan:
    enabled: true
    entry_min_rating: normal
    judge_scope: incoming
    judge_rules: []
    rules:
    - parts:
      - 武器
      - 环
      - 佩
      - 冠胄
      - 胸甲
      - 胫甲
      - 腕甲
      max_quality: purple
      max_pct: 100
      max_rating: junk
      action: recycle
  tune:
    enabled: true
    judge_scope: incoming
    judge_rules: []
    rules:
    - parts:
      - 武器
      - 环
      - 佩
      - 冠胄
      - 胸甲
      - 胫甲
      - 腕甲
      max_quality: purple
      max_pct: 100
      max_rating: junk
      action: recycle
    max_resets: 3
    reset_exhausted_action: recycle
