content_version: 1
martial_arts:
- name: 九重春色
  weapon: 伞
  attr: 牵丝
- name: 千香引魂蛊
  weapon: 伞
  attr: 牵丝
- name: 明川药典
  weapon: 扇
  attr: 牵丝
- name: 杏游草野
  weapon: 扇
  attr: 牵丝
- name: 青山执笔
  weapon: 扇
  attr: 牵丝
- name: 文动霓裳
  weapon: 舞绫鼓
  attr: 牵丝
- name: 醉梦游春
  weapon: 伞
  attr: 破竹
- name: 断水双诀
  weapon: 双刀
  attr: 破竹
- name: 泥犁三垢
  weapon: 双刀
  attr: 破竹
- name: 天志垂象
  weapon: 手甲
  attr: 破竹
- name: 悬身拳法
  weapon: 手甲
  attr: 破竹
- name: 千机索天
  weapon: 绳镖
  attr: 破竹
- name: 粟子游尘
  weapon: 绳镖
  attr: 破竹
- name: 粟子行云
  weapon: 绳镖
  attr: 破竹
- name: 八方风雷枪
  weapon: 枪
  attr: 裂石
- name: 斩雪刀法
  weapon: 横刀
  attr: 裂石
- name: 十方破阵
  weapon: 陌刀
  attr: 裂石
- name: 嗟夫刀法
  weapon: 陌刀
  attr: 裂石
- name: 无名剑法
  weapon: 剑
  attr: 鸣金
- name: 积矩九剑
  weapon: 剑
  attr: 鸣金
- name: 九曲惊神枪
  weapon: 枪
  attr: 鸣金
- name: 无名枪法
  weapon: 枪
  attr: 鸣金
