content_version: 1
playstyles:
- name: 火拳
  school: 牵丝·霖
  attr: 牵丝
  arts:
  - 明川药典
  - 千香引魂蛊
  main_weapon: 扇
  sub_weapon: 伞
  output_dingyin: 外功穿透
  defense_dingyin: ''
  main_damage: ''
  sub_damage: ''
  all_skill_requirement: 不需要
  qishu_requirement: 单体
  unit_requirement: 首领
- name: 纯奶
  school: 牵丝·霖
  attr: 牵丝
  arts:
  - 明川药典
  - 千香引魂蛊
  main_weapon: 扇
  main_damage: 扇武学增效
  sub_weapon: 伞
  output_dingyin: 外功穿透
  defense_dingyin: 明川药典治疗技增疗
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 玩家
- name: 纯唐
  school: 裂石·钧
  attr: 裂石
  arts:
  - 斩雪刀法
  - 十方破阵
  main_weapon: 横刀
  main_damage: 横刀武学增伤
  sub_weapon: 陌刀
  output_dingyin: 外功穿透
  defense_dingyin: 斩雪刀法轻重击派生技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 双切
  school: 裂石·钧
  attr: 裂石
  arts:
  - 斩雪刀法
  - 十方破阵
  main_weapon: 横刀
  main_damage: ''
  sub_weapon: 陌刀
  sub_damage: 陌刀武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 十方破阵蓄力技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 威威
  school: 裂石·威
  attr: 裂石
  arts:
  - 嗟夫刀法
  - 八方风雷枪
  main_weapon: 陌刀
  main_damage: 陌刀武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 嗟夫刀法蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 鸢鸢
  school: 破竹·鸢
  attr: 破竹
  arts:
  - 天志垂象
  - 千机索天
  main_weapon: 手甲
  main_damage: 手甲武学增伤
  sub_weapon: 绳镖
  output_dingyin: 外功穿透
  defense_dingyin: 天志垂象蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 双刀
  school: 破竹·风
  attr: 破竹
  arts:
  - 泥犁三垢
  - 粟子游尘
  main_weapon: 双刀
  main_damage: 双刀武学增伤
  sub_weapon: 绳镖
  sub_damage: 绳镖武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 粟子游尘鼠鼠增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 尘尘
  school: 破竹·尘
  attr: 破竹
  arts:
  - 醉梦游春
  - 粟子行云
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 绳镖
  output_dingyin: 外功穿透
  defense_dingyin: 醉梦游春武学技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
  sub_damage: ''
- name: 翊翊
  school: 牵丝·翊
  attr: 牵丝
  arts:
  - 文动霓裳
  - 杏游草野
  main_weapon: 舞绫鼓
  main_damage: 舞绫鼓武学增伤
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 文动霓裳特殊技增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
  sub_damage: ''
- name: 樽樽
  school: 破竹·樽
  attr: 破竹
  arts:
  - 悬身拳法
  - 断水双诀
  main_weapon: 手甲
  main_damage: 手甲武学增伤
  sub_weapon: 双刀
  sub_damage: 双刀武学增伤
  output_dingyin: 外功穿透
  defense_dingyin: 悬身断水·浓醺技能增伤
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 走地玉
  school: 牵丝·玉
  attr: 牵丝
  arts:
  - 九重春色
  - 青山执笔
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 九重春色高频弹道增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 单体
  unit_requirement: 首领
- name: 飞天玉
  school: 牵丝·玉
  attr: 牵丝
  arts:
  - 九重春色
  - 青山执笔
  main_weapon: 伞
  main_damage: 伞武学增效
  sub_weapon: 扇
  output_dingyin: 外功穿透
  defense_dingyin: 九重春色高频弹道增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 无名
  school: 鸣金·虹
  attr: 鸣金
  arts:
  - 无名剑法
  - 无名枪法
  main_weapon: 剑
  main_damage: 剑武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 无名剑法蓄力技增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 不需要
  unit_requirement: 首领
- name: 九剑
  school: 鸣金·影
  attr: 鸣金
  arts:
  - 积矩九剑
  - 九曲惊神枪
  main_weapon: 剑
  main_damage: 剑武学增伤
  sub_weapon: 枪
  output_dingyin: 外功穿透
  defense_dingyin: 积矩九剑流血增伤
  sub_damage: ''
  all_skill_requirement: 需要
  qishu_requirement: 单体
  unit_requirement: 首领
